### ISSUE TITLE
FATAL: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by adeklanin** [modoboa/modoboa#1005]
Hello,

First I'm gonna say thanks @tonioo and all contributors for Modoboa, it helped me move from our old and heavy Zimbra Java based mail server to.. I would say modern, and yet simple Modoboa.

Btw all of mail server terminology are new stuff for me, but I've done my homework, reading, testing configuring, debugging, and so on. So please don't be to harsh on me.

Specs:
- Install using installer
- Debian 8.6 on 4Gb DigitalOcean VM
- PostgreSQL as Database
- most of the extensions, except: Radicale and IMAP Migration

After deploying Modoboa for almost a week, and I'm getting this error:

```
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 67, in ready
    load_core_settings()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/apps.py", line 55, in load_core_settings
    parameters.register(GeneralParametersForm, ugettext_lazy("General"))
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 192, in register
    form = formclass()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/app_settings.py", line 304, in __init__
    super(GeneralParametersForm, self).__init__(*args, **kwargs)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 62, in __init__
    self._load_initial_values()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/parameters.py", line 96, in _load_initial_values
    if not db_utils.db_table_exists("lib_parameter"):
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/db_utils.py", line 12, in db_table_exists
    return table in connection.introspection.table_names()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 56, in table_names
    with self.connection.cursor() as cursor:
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

This message actually delivered to the admin account I've setup, to receive error message from the services. So far from what I read, this issue are related to PostgreSQL, and I see on [dovecot-sql-postgres.conf.ext.tpl](https://github.com/modoboa/modoboa-installer/blob/81b32d21ad723a2706e7111378395b164ba91142/modoboa_installer/scripts/files/dovecot/dovecot-sql-postgres.conf.ext.tpl) that we could add to **dovecot-sql-postgres.conf.ext** `maxconns` increase value from default `5` for example to `10` or `20`.

Also theres this value `max_connections` and `superuser_reserved_connections` on **postgresql.conf**, are `max_connections` need to be the same value with `maxconns` from **dovecot-sql-postgres.conf**? Or is there some kind of rule about this value, which one should we tune first or should we do both?

I already doubled both `maxconns` and `max_connections` value from default, need to test when high traffic tomorrow morning. While waiting, are there any suggestion about this issue?

**Comment by tonioo** [comment]
@adeklanin I think it is related to postfix which opens too many connections to the database. I'll fix that.

By the way, this issue is related to the installer so could you please move it to the appropriate repository? Thank you.

**Comment by adeklanin** [comment]
@tonioo done. Copied to [modoboa/modoboa-installer#92](https://github.com/modoboa/modoboa-installer/issues/92)

**Comment by tonioo** [comment]
Thank you.
