### ISSUE TITLE
Test failures when using tox

### ISSUE THREAD

**Issue by gawel** [modoboa/modoboa#1121]
# Impacted versions

* Modoboa: master

# Steps to reproduce

checkout
run tox

# Current behavior

```
py27 runtests: commands[1] | coverage run --source modoboa manage.py test modoboa.core modoboa.lib modoboa.admin.tests modoboa.limits modoboa.relaydomains
Creating test database for alias 'default'...
.........................sss.EEEE.......................................s........EEE................................................................Cannot upgrade 'sql-domains.cf' map because it has been modified.
...........................................................
======================================================================
ERROR: test_smtp_authentication (modoboa.core.tests.test_authentication.SMTPAuthenticationTestCase)
Check simple SMTP authentication.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/tests.py", line 59, in setUp
    self.client.login(username=username, password=password), True)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/django/test/client.py", line 621, in login
    user = authenticate(**credentials)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/authbackends.py", line 28, in authenticate
    smtp = smtplib.SMTP(host, port)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

======================================================================
ERROR: test_smtp_authentication_failure (modoboa.core.tests.test_authentication.SMTPAuthenticationTestCase)
Check SMTP authentication failure.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/tests.py", line 59, in setUp
    self.client.login(username=username, password=password), True)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/django/test/client.py", line 621, in login
    user = authenticate(**credentials)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/authbackends.py", line 28, in authenticate
    smtp = smtplib.SMTP(host, port)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

======================================================================
ERROR: test_smtp_authentication_over_ssl (modoboa.core.tests.test_authentication.SMTPAuthenticationTestCase)
Check SMTP authentication over SSL.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/tests.py", line 59, in setUp
    self.client.login(username=username, password=password), True)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/django/test/client.py", line 621, in login
    user = authenticate(**credentials)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/authbackends.py", line 28, in authenticate
    smtp = smtplib.SMTP(host, port)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

======================================================================
ERROR: test_smtp_authentication_over_starttls (modoboa.core.tests.test_authentication.SMTPAuthenticationTestCase)
Check SMTP authentication over STARTTLS.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/tests.py", line 59, in setUp
    self.client.login(username=username, password=password), True)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/django/test/client.py", line 621, in login
    user = authenticate(**credentials)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/authbackends.py", line 28, in authenticate
    smtp = smtplib.SMTP(host, port)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/home/gawel/.pyenv/versions/2.7.9/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

======================================================================
ERROR: test_delete_account (modoboa.admin.tests.test_mailbox_operations.MailboxOperationTestCase)
Check delete operation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/admin/tests/test_mailbox_operations.py", line 36, in setUp
    self.set_global_parameter("handle_mailboxes", True)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/tests.py", line 36, in set_global_parameter
    self.localconfig.parameters.set_value(name, value, app=app)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/parameters/tools.py", line 139, in set_value
    raise NotDefined(app, parameter)
NotDefined: Parameter handle_mailboxes not defined for app admin

======================================================================
ERROR: test_delete_domain (modoboa.admin.tests.test_mailbox_operations.MailboxOperationTestCase)
Check delete operation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/admin/tests/test_mailbox_operations.py", line 36, in setUp
    self.set_global_parameter("handle_mailboxes", True)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/tests.py", line 36, in set_global_parameter
    self.localconfig.parameters.set_value(name, value, app=app)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/parameters/tools.py", line 139, in set_value
    raise NotDefined(app, parameter)
NotDefined: Parameter handle_mailboxes not defined for app admin

======================================================================
ERROR: test_rename_account (modoboa.admin.tests.test_mailbox_operations.MailboxOperationTestCase)
Check rename operation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/admin/tests/test_mailbox_operations.py", line 36, in setUp
    self.set_global_parameter("handle_mailboxes", True)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/lib/tests.py", line 36, in set_global_parameter
    self.localconfig.parameters.set_value(name, value, app=app)
  File "/home/gawel/bear/modoboa/.tox/py27/lib/python2.7/site-packages/modoboa/parameters/tools.py", line 139, in set_value
    raise NotDefined(app, parameter)
NotDefined: Parameter handle_mailboxes not defined for app admin

----------------------------------------------------------------------
Ran 207 tests in 69.291s
```

# Expected behavior

No errors

I guess smtp related tests must be skipped when using tox.

Don't know for the others.

**Comment by tonioo** [comment]
SMTP related tests require a SMTP server to be installed locally...

**Comment by gawel** [comment]
That's what I thought :) Then they should be skipped when no smtp run locally. Like for the LDAP tests.

**Comment by gawel** [comment]
After applying #1126  I still have three failures about ```NotDefined: Parameter handle_mailboxes not defined for app admin```. Any hint ?
