### ISSUE TITLE
Failed installer on first try.

### ISSUE THREAD

**Issue by ken-sands** [modoboa/modoboa#1188]
# Impacted versions

* Modoboa: installer
* installer used: Yes
* Webserver: Apache
* CentOS 6.9

# Steps to reproduce
I followed the instructions on the modoboa from page, git clone followed by cd followed by ./run.py
on the ./run.py it fails

# Current behavior
Traceback (most recent call last):
  File "./run.py", line 12, in <module>
    from modoboa_installer import package
  File "/home/ken/modoboa-installer/modoboa_installer/package.py", line 105, in <module>
    backend = get_backend()
  File "/home/ken/modoboa-installer/modoboa_installer/package.py", line 102, in get_backend
    return backend(distname)
  File "/home/ken/modoboa-installer/modoboa_installer/package.py", line 71, in __init__
    self.install("epel-release")
  File "/home/ken/modoboa-installer/modoboa_installer/package.py", line 75, in install
    utils.exec_cmd("yum install -y --quiet {}".format(name))
ValueError: zero length field name in format

# Expected behavior
An install, or at least an error message I can work with without knowing the code.

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-installer#144
