### ISSUE TITLE
Cronjob fails  $PYTHON $INSTANCE/manage.py update_statistics

### ISSUE THREAD

**Issue by TonyBostonTB** [modoboa/modoboa#1244]
# Impacted versions

* Modoboa: 1.9.0
* installer used: Yes
* Webserver: Nginx
* OS: Centos 7
* DB: Postgresql

# Traceback

```
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_stats/management/commands/update_statistics.py", line 84, in handle
    self.update_account_creation_stats(options["rebuild"])
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_stats/management/commands/update_statistics.py", line 79, in update_account_creation_stats
    rrdtool.update(str(db_path), *data)
rrdtool.OperationalError: /srv/modoboa/rrdfiles/new_accounts.rrd: illegal attempt to update using time 1505988000 when last update time is 1505988000 (minimum one second step)
```

**Comment by tonioo** [comment]
Looks like the cron job is running twice at the same time... Did you install modoboa manually?

**Comment by TonyBostonTB** [comment]
nope, I used the installer

**Comment by tonioo** [comment]
Do you see this error each time the command is executed?
Can you please check the cron job definition inside ``/etc/cron.d/modoboa``, it should run every 5 minutes.

**Comment by sorcer1122** [comment]
I am also having the very same error but I suspect this is because I added 'manage.py update_statistics' to crontab file. This is not required, is it?

**Comment by tonioo** [comment]
@sorcer1122 This is indeed optional but you're seeing this error because the RRD file is updated twice for the same timestamp. How did you configure the crontab?

**Comment by sorcer1122** [comment]
@tonioo I had the following in my crontab:

0 * * * * /srv/modoboa/instance/manage.py update_statistics

Once I commented it out, the error disappeared. Most probably because /etc/cron.d/modoboa had the same string.

**Comment by tonioo** [comment]
@TonyBostonTB Can you check the /etc/cron.d/modoboa to check if the update_statistics command appears only once?

**Comment by kryskool** [comment]
ping @TonyBostonTB
