### ISSUE TITLE
Graph Is not Appear The Cron Job no error

### ISSUE THREAD

**Issue by nizammufid** [modoboa/modoboa#1348]
# Impacted versions
* Modoboa: 1.9.1
* installer used: Yes
* Webserver: Nginx

Jan 11 13:40:01 MailServer02 CRON[8743]: (root) CMD (   $PYTHON $INSTANCE/manage.py logparser &> /dev/null)

the Cron job is running but the Graphical Statistic is empty there have many Mail flow there Please help

**Comment by fyfe** [comment]
Can you ensure that the mail log file and rrd directory are correct under the Graphical statistics settings.

Also if you are using the default rrd directory `/tmp/modoboa` unsure your operating system isn't deleting everything under /tmp on a regular bases.

How long have you had the cron job enabled for? For a new stats rrd it can take a little while before the graphs start updating.

**Comment by nizammufid** [comment]
I see it appear the graph but Root Account got and Email regarding error 

Subject: Cron <root@MailServer02>    $PYTHON $INSTANCE/manage.py update_statistics
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <PYTHON=/srv/modoboa/env/bin/python>
X-Cron-Env: <INSTANCE=/srv/modoboa/instance>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
Message-Id: <20180112060004.470FC5625A8@mail.peoplesbay.com>
Date: Fri, 12 Jan 2018 14:00:04 +0800 (+08)

Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_stats/management/commands/update_statistics.py", line 84, in handle
    self.update_account_creation_stats(options["rebuild"])
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_stats/management/commands/update_statistics.py", line 79, in update_account_creation_stats
    rrdtool.update(str(db_path), *data)
rrdtool.OperationalError: /srv/modoboa/rrdfiles/new_accounts.rrd: illegal attempt to update using time 1515733200 when last update time is 1515733200 (minimum one second step)

Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Comment by tonioo** [comment]
Have you run the command manually? 

This RRD file is configured with a 60 minutes step and the error says the script is trying to record a point for a timestamp which has already been recorded...

**Comment by nizammufid** [comment]
i already solve the issue Tks

**Comment by DEK4** [comment]
Hello,
how you solved this problem?

I get the same thing

Thanks
