### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by kev1904** [modoboa/modoboa#1387]
* Modoboa: 1.8.2
* installer used: Yes ?
* Webserver: Nginx
* System  Ubuntu 16.04.3 LTS
--
Hello,
I would update from  1.8.2 to 1.10.1 using the Toturial in the Docu. 

I get an issue after use "python manage.py migrate"

`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/modoboa_amavis/apps.py", line 13, in ready
    from . import handlers
  File "/usr/local/lib/python2.7/dist-packages/modoboa_amavis/handlers.py", line 21, in <module>
    from . import forms
  File "/usr/local/lib/python2.7/dist-packages/modoboa_amavis/forms.py", line 16, in <module>
    class DomainPolicyForm(forms.ModelForm):
  File "/usr/local/lib/python2.7/dist-packages/modoboa_amavis/forms.py", line 20, in DomainPolicyForm
    class Meta:
  File "/usr/local/lib/python2.7/dist-packages/modoboa_amavis/forms.py", line 26, in Meta
    'bypass_virus_checks': form_utils.InlineRadioSelect(),
AttributeError: 'module' object has no attribute 'InlineRadioSelect'
`

**Comment by tonioo** [comment]
@kev1904 Have you updated extensions before launching the command? (as explained in the documentation)

**Comment by kev1904** [comment]
Yes ive run pip install modoboa==1.10.1

**Comment by tonioo** [comment]
Ok so you did not follow the upgrade procedure... http://modoboa.readthedocs.io/en/latest/upgrade.html#id2
