### ISSUE TITLE
ImportError: No module named compat

### ISSUE THREAD

**Issue by mkkeck** [modoboa/modoboa#1394]
### Impacted versions

* Modoboa: 1.10.2
* installer used: Yes
* Webserver: Apache

### Steps to reproduce
Update from 1.9.x to 1.10.2

### Current behavior
I've got an email:
```
Subject: Cron <root@host>         $PYTHON $INSTANCE/manage.py modo check_mx
/* [...] blabla [...] */
X-Cron-Env: <PYTHON=/.../modoboa/env/bin/python>
X-Cron-Env: <INSTANCE=/.../modoboa/instance>
Message-Id: <msgid@example.net>

Traceback (most recent call last):
  File "/.../modoboa/instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/.../modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/.../modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/.../modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/.../modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/.../modoboa/env/lib/python2.7/site-packages/modoboa/admin/management/commands/modo.py", line 10, in <module>
    from .subcommands._import import ImportCommand
  File "/.../modoboa/env/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_import.py", line 10, in <module>
    import progressbar
  File "/.../modoboa/env/lib/python2.7/site-packages/progressbar/__init__.py", line 58, in <module>
    from progressbar.compat import *
ImportError: No module named compat

```
### Try to fix but without success:
```
> sudo -u <modoboa_user> -i
> source <virtuenv_path>/bin/activate
> pip install --upgrade pip
> pip install django-compat
```

**Comment by tonioo** [comment]
Please make sure to install the latest version of the progressbar33 package instead of the progressbar one. If both are installed in your virtualenv, uninstall progressbar.

**Comment by mkkeck** [comment]
Tonioo thanks a lot.
