### ISSUE TITLE
Administrator cannot log in

### ISSUE THREAD

**Issue by jing95** [modoboa/modoboa#1423]
# Impacted versions

* Modoboa: 1.10.1
* installer used: Yes
* Webserver: Nginx

# Current behavior
When I log in as an administrator, I always say 504. But if it's a normal user, everything is fine.
# Expected behavior
 I can log in as administrator

**Comment by jing95** [comment]
There is the traceback:

Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_amavis/apps.py", line 19, in ready
    from . import handlers  # noqa:F401
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_amavis/handlers.py", line 25, in <module>
    from . import forms
ImportError: cannot import name forms

**Comment by jing95** [comment]
From root@mail.iat.cool  Mon Mar  5 10:00:50 2018
Return-Path: <root@mail.iat.cool>
X-Original-To: root
Delivered-To: root@mail.iat.cool
Received: by mail.iat.cool (Postfix, from userid 0)
        id 281D34078B93; Mon,  5 Mar 2018 02:00:50 +0000 (UTC)
From: "(Cron Daemon)" <root@mail.iat.cool>
To: root@mail.iat.cool
Subject: Cron <root@iatcool>    $PYTHON $INSTANCE/manage.py communicate_with_public_api
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=79157>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <PYTHON=/srv/modoboa/env/bin/python>
X-Cron-Env: <INSTANCE=/srv/modoboa/instance>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20180305020050.281D34078B93@mail.iat.cool>
Date: Mon,  5 Mar 2018 02:00:49 +0000 (UTC)

CommandError: Failed to retrieve versions from the API.
