### ISSUE TITLE
logparser fails to create RRD directory

### ISSUE THREAD

**Issue by cptMikky** [modoboa/modoboa#1424]
# Impacted versions

* Modoboa: 1.10.3
* installer used: No
* Webserver: Nginx (irrelevant)

# Steps to reproduce
```
root@server# /path/to/venv/bin/python /path/to/modoboa/instance/manage.py logparser
```
# Current behavior
```
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/app/modoboa/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/app/modoboa/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/app/modoboa/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/app/modoboa/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/app/modoboa/venv/local/lib/python2.7/site-packages/modoboa_stats/management/commands/logparser.py", line 588, in handle
    p.process()
  File "/srv/app/modoboa/venv/local/lib/python2.7/site-packages/modoboa_stats/management/commands/logparser.py", line 559, in process
    self.update_rrd(dom, t)
  File "/srv/app/modoboa/venv/local/lib/python2.7/site-packages/modoboa_stats/management/commands/logparser.py", line 257, in update_rrd
    self.lupdates[fname] = self.init_rrd(fname, m)
  File "/srv/app/modoboa/venv/local/lib/python2.7/site-packages/modoboa_stats/management/commands/logparser.py", line 215, in init_rrd
    *params)
rrdtool.OperationalError: Cannot create temporary file
```
RRD storage directory does not exist and *logparser* probably doesn't even try to create it. 

# Expected behavior

Parse log and create RRD files. Create the necessary directory structure and fail properly if that isn't possible.

Command works as expected after the directory is created manually.

**Comment by tonioo** [comment]
@cptMikky I don't think the script should be responsible for creating the directory structure. A better option would be to ensure the directory exists when the global setting is modified. What do you think?

**Comment by cptMikky** [comment]
Not sure. Directory structure, especially in /tmp is definitely a responsibility of the owner (the script in this scenario). As for other places, well, hard to tell, I have no single opinion.

However, a directory existence test and a (sane) error message would be enough I guess.

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-stats#40
