### ISSUE TITLE
"deploy instance" failed

### ISSUE THREAD

**Issue by haolle** [modoboa/modoboa#1437]
# Impacted versions

* Modoboa: 1.10.3
* installer used: No ?
* Webserver: 

# Steps to reproduce

$ modoboa-admin.py deploy instance --collectstatic --domain mail.peop.com --dburl default:postgres://dev:dev@localhost:5432/peopmail

# Current behavior
Traceback (most recent call last):
File "/home/dd/anaconda3/envs/py35mail/bin/modoboa-admin.py", line 9, in
handle_command_line()
File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/modoboa/core/commands/init.py", line 87, in handle_command_line
commands = scan_for_commands()
File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/modoboa/core/commands/init.py", line 70, in scan_for_commands
[smart_str(cmdname)])
File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/modoboa/core/commands/deploy.py", line 27, in
import pip
File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/pip/init.py", line 45, in
from pip.vcs import git, mercurial, subversion, bazaar # noqa
File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/pip/vcs/mercurial.py", line 9, in
from pip.download import path_to_url
File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/pip/download.py", line 40, in
from pip._vendor import requests, six
File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/pip/_vendor/requests/init.py", line 98, in
from . import packages
File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/pip/_vendor/requests/packages.py", line 12, in
sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'

# Expected behavior
  modoboa installed.

Hi guys, not sure if it is a bug. It is a fresh env: python3.5.4 + modoboa1.10.3
even i run ''help deploy", it generates similar issue.

**Comment by maisim** [comment]
Seems to be a bug with pip 9.0.2 (released 2 days ago)
https://github.com/pypa/pip/issues/5079
Can you try with pip 9.0.1 ?
 pip install pip==9.0.1

**Comment by fyfe** [comment]
@haolle try deleting the pip cache in ```~/.cache/pip```

**Comment by haolle** [comment]
yeah, I downgraded pip to 9.0.1 and reinstalled modoboa, and then the instance deployment process passed.
thanks for all replies and suggestions.

**Comment by haolle** [comment]
As I already have ngix and postgres installed, so I chose manual installation.
After running deployment command, and try to configure cron jobs, I cannot locate modoboa instance. Can anyone tell the instance path? I did some search but no result.
thanks.

**Comment by haolle** [comment]
manually install modoboa.
cannot locate modoboa instance to configure cron file. can anyone tell the instance path?
thanks.

**Comment by haolle** [comment]
alright, i found it in current folder where i ran the deploy command. instance folder name is "instance".

**Comment by maisim** [comment]
#1439

**Comment by kryskool** [comment]
The PR #1439 have been merged
I close this issue
