### ISSUE TITLE
Check_MX

### ISSUE THREAD

**Issue by TomasOlsson** [modoboa/modoboa#1515]
# Impacted versions

* Modoboa: 1.10.5
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
When running: /srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo check_mx

# Current behavior
Gets error:

```
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/subcommand/base.py", line 53, in run_from_argv
    return super(SubcommandCommand, self).run_from_argv(argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/subcommand/base.py", line 84, in handle
    return command.run_from_argv(argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 244, in handle
    self.check_domain(domain, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 194, in check_domain
    self.check_valid_mx(domain, mx_list, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 153, in check_valid_mx
    valid_mxs = self.valid_mxs
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 47, in valid_mxs
    for v in valid_mxs.split() if v.strip()]
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/ipaddress.py", line 204, in ip_network
    address)
ValueError: u'mail.rally24.se' does not appear to be an IPv4 or IPv6 network
```
Error in ModoBoa log: DNS resolution timeout, unable to query printartsnovabellis.se at the moment
# Expected behavior

# Video/Screenshot link (optional)
https://imgur.com/a/tYicMCf

**Comment by TomasOlsson** [comment]
Found the problem. Some how it was checking mail.rally24.se not the IP :S

**Comment by InToSSH** [comment]
I have exactly the same problem. How did you fix it? It worked at first, but then I changed the MX record and this happend.

**Comment by dakota** [comment]
@TomasOlsson How did you fix this?

**Comment by harryfoster** [comment]
I'm aware this is relatively old now, but I hate seeing un-explained issues on the internet. I managed to experience the same when I misread the 'Valid MX' parameter and put an actual MX record in domain form into the field. Replacing this with a list of IP addresses rectified it.
