### ISSUE TITLE
can't create identities (new fresh install with apache)

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa#1547]
Hi all,

Subject says it all. No identities can be created. I am using appache currently and will also test it with nginx and report here.

cheers,
JBR

# Impacted versions

* Modoboa: 1.10.6
* installer used: Yes
* Webserver: Apache

# Steps to reproduce

 * Open the webinterface go to identities and click on '+Add'
 * Fill in the required fields, press, 'Next' and 'Submit'

# Current behavior

No result. The dialog windows with the 'Submit' button stays on screen.

# Expected behaviour

Create an identity (i.e. user in this case)

# Javascript Console, output
```

 [Show/hide message details.] SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jquery.min.js:3:4315
parseJSON
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:4315
post/<
https://mail.nerderlands.net/sitestatic/js/creation_wizard.js:61:28
i
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:6334
c
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:7852
fireWith
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:8658
k
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:5:14038
r
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:5:18226
[Show/hide message details.] SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jquery.min.js:3:4315
parseJSON
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:4315
post/<
https://mail.nerderlands.net/sitestatic/js/creation_wizard.js:61:28
i
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:6334
c
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:7852
fireWith
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:8658
k
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:5:14038
r
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:5:18226
[Show/hide message details.] SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jquery.min.js:3:4315
parseJSON
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:4315
post/<
https://mail.nerderlands.net/sitestatic/js/creation_wizard.js:61:28
i
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:6334
c
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:7852
fireWith
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:3:8658
k
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:5:14038
r
https://mail.nerderlands.net/sitestatic/jquery/jquery.min.js:5:18226

```

**Comment by JayBeRayBearGun** [comment]
Aha,.. using nginx it works,... Could it be that apache can't access the pdfcredentials directory perhaps?

How do I fix this if this indeed is the case? Add a corresponding directory stanza?

```
<VirtualHost *:443>
  ServerName mail.nerderlands.net
  DocumentRoot /srv/modoboa/instance/

  Alias /media/ /srv/modoboa/instance/media/
  <Directory /srv/modoboa/instance/media>
    Require all granted
  </Directory>

  Alias /sitestatic/ /srv/modoboa/instance/sitestatic/
  <Directory /srv/modoboa/instance/sitestatic>
    Require all granted
  </Directory>

  WSGIScriptAlias / /srv/modoboa/instance/instance/wsgi.py
  WSGIDaemonProcess mail.nerderlands.net python-path=/srv/modoboa/instance:/srv/modoboa/env/lib/python2.7/site-packages
  WSGIProcessGroup mail.nerderlands.net

  # Pass Authorization header to enable API usage:
  WSGIPassAuthorization On
</VirtualHost>

```

**Comment by JayBeRayBearGun** [comment]
Using apache to delete the just created identity I get this response at the top of the browser:

```
Failed to retrieve mailbox location ( We trust you have received the
usual lecture from the local System Administrator. It usually boils
down to these three things: #1) Respect the privacy of others. #2)
Think before you type. #3) With great power comes great
responsibility. sudo: no tty present and no askpass program specified
)


```

**Comment by JayBeRayBearGun** [comment]
PS: the apache.conf already contains this,... 

```
<Directory /srv/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

```

**Comment by tonioo** [comment]
@JayBeRayBearGun Looks like the user running apache has not the permission to run doveadm.

**Comment by JayBeRayBearGun** [comment]
Hi Antoin,

Thanks for the response. 

That would be www-data the same user as nginx is using. What else could it be? How can I test this?  By the way I tried the DEBUG=True but where do I find the output? In the browser?

JBR

**Comment by tonioo** [comment]
Look at this: http://modoboa.readthedocs.io/en/latest/configuration.html#host-configuration (check your sudoers file).

**Comment by JayBeRayBearGun** [comment]
Hmm,.. did as directed. Restarted webserver, uwsgi etc. Also turned DEBUG=True no succes no output

**Comment by ByteSizedMarius** [comment]
Sorry for bumping this 3yr old thread, but I had the exact same problem and as this is the first resource you find on google, I would like to maybe help the next desperate person searching for the answer. 
My problem was that the www-data user didnt have any perms for the /srv/modoboa/pdfcredentials/ directory. chowning it/ giving it perms manually fixed it for me.

**Comment by kiloDE** [comment]
> Sorry for bumping this 3yr old thread, but I had the exact same problem and as this is the first resource you find on google, I would like to maybe help the next desperate person searching for the answer.
> My problem was that the www-data user didnt have any perms for the /srv/modoboa/pdfcredentials/ directory. chowning it/ giving it perms manually fixed it for me.

Same weirdity occured here. I did the same. In my case **chmod 755 -R /srv/modoboa/pdfcredentials** was **NOT** enough.
Sadly it's so annoying you need 7777 otherwise the admin panel won't create the user (why ever!)
