### ISSUE TITLE
Modoboa 1.10.7 upgrade message

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1574]
Hello!

Is the following CommandError "normal"?

```
Installing collected packages: modoboa
  Found existing installation: modoboa 1.10.6
    Uninstalling modoboa-1.10.6:
      Successfully uninstalled modoboa-1.10.6
Successfully installed modoboa-1.10.7
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env) modoboa@mail:~$ cd instance
(env) modoboa@ mail:~/instance$ python manage.py migrate
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0016_auto_20180713_1014, 0016_auto_20180723_0804 in core).
To fix them run 'python manage.py makemigrations --merge'

```

**Comment by stefaweb** [comment]
And the next message.

```
(env) modoboa@mail:~/instance$ python manage.py makemigrations --merge
Merging core
  Branch 0016_auto_20180713_1014
    - Alter field language on user
  Branch 0016_auto_20180723_0804
    - Alter field language on user

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N]

```

**Comment by tonioo** [comment]
Looks like you ran a ``makemigrations`` command in July, which generated the 0016_auto_20180723_0804 migration. **You should not run this command yourself**, all migrations are normally provided by Modoboa but there was an issue in July which was fixed by version 1.10.6.

The only good fix here is to:
* Rollback core migrations to version 0015
* Remove the migration you created
* Apply official migrations

You can run the following commands:
```shell
> python manage.py migrate core 0015
> rm /srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/migrations/0016_auto_20180723_0804.py*
> python manage.py migrate
```
```

**Comment by stefaweb** [comment]
Not good for me.

```
root@ mail:/home/sleclerc# sudo -u modoboa -i
$ bash
modoboa@ mail:~$ cd instance
modoboa@ mail:~/instance$ python manage.py migrate core 0015
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

```

**Comment by tonioo** [comment]
@stefaweb You must load the virtualenv first:
```shell
> source ~/env/bin/activate
```

**Comment by stefaweb** [comment]
A little better but boom again later after with `python manage.py migrate`.

```
modoboa@mail:~/instance$ source ~/env/bin/activate
(env) modoboa@mailhub:~/instance$ python manage.py migrate core 0015
Operations to perform:
  Target specific migration: 0015_auto_20180112_1642, from core
Running migrations:
  Rendering model states... DONE
  Unapplying core.0017_merge_20181002_1351... OK
  Unapplying core.0016_auto_20180713_1014... OK
  Unapplying core.0016_auto_20180723_0804... OK
(env) modoboa@mailhub:~/instance$ rm /srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/migrations/0016_auto_20180723_0804.py*
(env) modoboa@mailhub:~/instance$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
django.db.migrations.exceptions.NodeNotFoundError: Migration core.0017_merge_20181002_1351 dependencies reference nonexistent parent node (u'core', u'0016_auto_20180723_0804')

```

**Comment by tonioo** [comment]
You also need to remove the merge migration you just created: 0017_merge_20181002_1351.

**Comment by stefaweb** [comment]
Good this time.

```
(env) modoboa@ mail:~/instance$ rm /srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/migrations/0017_merge_20181002_1351.py*
(env) modoboa@mail:~/instance$ python manage.py migrate core
Operations to perform:
  Apply all migrations: core
Running migrations:
  Applying core.0016_auto_20180713_1014... OK

```

`./run.py --upgrade` will be welcome. ;-)

With do we have to remove `proxy:mysql:/etc/postfix/sql-autoreplies-transport.cf` from relay_domains and proxy_read_maps for auto reply 1.5.0 ?

**Comment by stefaweb** [comment]
Ok, I close. Thanks.

For autoreply, this is `/api/v1/armessages/` in API?

Will try to work on the RoundCube vacation plugin next week.

**Comment by tonioo** [comment]
Yes.
