### ISSUE TITLE
Lost admin password

### ISSUE THREAD

**Issue by OliverGee** [modoboa/modoboa#1617]
# Impacted versions

* Modoboa: Latest (installed 2 days ago)
* installer used: Yes/No ? Yes
* Webserver: Nginx/Apache

# Steps to reproduce
Lose your admin password...

# Current behavior
I've tried utilising the methods from this thread: 

https://github.com/modoboa/modoboa/issues/905

Each time, i receive: "Couldn't import Django. Are you sure it's installed and "

Whenever i try to recover the password, i never receive an email (despite correctly setting both Primary and Secondary emails).

**Comment by tonioo** [comment]
@OliverGee Make sure the python virtual is loaded before running the changepassword command:
```shell
> source /srv/modoboa/env/bin/activate
```

**Comment by OliverGee** [comment]
@tonioo Thanks for the swift response. As you may be able to tell, this is not my area of expertise.

That did work (I got a change password prompt by using your snippet from the other thread), however i received this output and the new password doesn't work:

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/changepassword.py", line 75, in handle
    u.set_password(p1)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/models.py", line 134, in set_password
    account=self, password=raw_value, created=self.pk is None)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pdfcredentials/handlers.py", line 22, in password_updated
    "generate_at_creation")
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/parameters/tools.py", line 186, in get_global_parameter
    return get_localconfig().parameters.get_value(name, app=app, **kwargs)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/parameters/tools.py", line 121, in get_value
    default = registry.get_default(self._level, app, parameter)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/parameters/tools.py", line 90, in get_default
    raise NotDefined(app)
modoboa.parameters.tools.NotDefined: Application modoboa_pdfcredentials not registered
```

**Comment by OliverGee** [comment]
Hi @toniool.

Password changed successfully! Thank you for your help.

**Comment by reduxionist** [comment]
This issue persists as of Modoboa version 1.14 / PDF Credentials 1.3.2, installed using installer, but given workaround also still works. :)

**Comment by Naznouz** [comment]
Dear Modoboa team,
Is this issue solved ?
I'm still facing the exact same problem with Modoboa 2.2.6
Thanks
