### ISSUE TITLE
modoboa_dnsrecord relation not found

### ISSUE THREAD

**Issue by BigMichi1** [modoboa/modoboa#1649]
# Impacted versions

* Modoboa: 1.13.0
* installer used: No ?
* Webserver: Nginx

# Steps to reproduce

after upgrading to 1.13.0 there is a relation error when running check_mx

```python manage.py migrate``` shows

    Operations to perform:
      Apply all migrations: admin, auth, authtoken, contenttypes, core, lib, limits, modoboa_amavis, relaydomains, reversion, sessions, sites, transport
    Running migrations:
      No migrations to apply.

failing command is 

```python manage.py modo check_mx```

# Current behavior

fails with relation not found

    Traceback (most recent call last):
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    psycopg2.ProgrammingError: relation "modoboa_dnsrecord" does not exist
    LINE 1: ...cord"."error", "modoboa_dnsrecord"."updated" FROM "modoboa_d...
                                                                 ^
    
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "manage.py", line 22, in <module>
        execute_from_command_line(sys.argv)
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
        utility.execute()
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/srv/modoboa/env/lib/python3.6/site-packages/subcommand/base.py", line 53, in run_from_argv
        return super(SubcommandCommand, self).run_from_argv(argv)
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
        output = self.handle(*args, **options)
      File "/srv/modoboa/env/lib/python3.6/site-packages/subcommand/base.py", line 84, in handle
        return command.run_from_argv(argv)
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
        output = self.handle(*args, **options)
      File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 264, in handle
        self.check_domain(domain, **options)
      File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 199, in check_domain
        domain, "spf", ttl)
      File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/dnstools/models.py", line 26, in get_or_create_for_domain
        domain=domain, type=rtype, updated__gt=now).first()
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/models/query.py", line 567, in first
        objects = list((self if self.ordered else self.order_by('pk'))[:1])
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __iter__
        self._fetch_all()
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/models/query.py", line 1121, in _fetch_all
        self._result_cache = list(self._iterable_class(self))
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
        results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
        raise original_exception
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
        cursor.execute(sql, params)
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/srv/modoboa/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    django.db.utils.ProgrammingError: relation "modoboa_dnsrecord" does not exist
    LINE 1: ...cord"."error", "modoboa_dnsrecord"."updated" FROM "modoboa_d...
     

# Expected behavior

should not fail

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@BigMichi1 Looks like you forgot to apply 1.13.0 dedicated instructions: https://modoboa.readthedocs.io/en/latest/upgrade.html#id2.
