### ISSUE TITLE
Bug when Upgrading

### ISSUE THREAD

**Issue by Th0rGer** [modoboa/modoboa#1651]
# Impacted versions

* Modoboa: 1.12.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
 Try to upgrade
# Current behavior
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/instance/instance/settings.py", line 331, in <module>
    from modoboa_amavis import settings as modoboa_amavis_settings
ImportError: No module named modoboa_amavis
# Expected behavior
 ...

**Comment by tonioo** [comment]
@Th0rGer you forgot to load the virtualenv before running the migration process. Please consult the documentation: https://modoboa.readthedocs.io/en/latest/upgrade.html.
I know the upgrade process is a bit tricky but there is an open sponsoring (https://modoboa.org/en/projects/8/) to improve it.
