### ISSUE TITLE
Traceback: check_mx

### ISSUE THREAD

**Issue by cremesk** [modoboa/modoboa#1664]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

/srv/modoboa/env/bin/python /srv/modoboa/instance/manage.py modo check_mx

Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/subcommand/base.py", line 53, in run_from_argv
    return super(SubcommandCommand, self).run_from_argv(argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/subcommand/base.py", line 84, in handle
    return command.run_from_argv(argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 264, in handle
    self.check_domain(domain, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 195, in check_domain
    self.check_valid_mx(domain, mx_list, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 154, in check_valid_mx
    valid_mxs = self.valid_mxs
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 48, in valid_mxs
    for v in valid_mxs.split() if v.strip()]
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/ipaddress.py", line 204, in ip_network
    address)
ValueError: u'mail.secnux.net' does not appear to be an IPv4 or IPv6 network

**Comment by tonioo** [comment]
@cremesk The "valid mxs" option should only contain ip addresses, not domain names.

**Comment by tuxis-ie** [comment]
Which is kinda weird, considering mx records are defined in hostnames, not IP addresses..?

**Comment by tonioo** [comment]
@tuxis-ie The comparison is done after name resolution.

**Comment by kryskool** [comment]
I think in this case we can add a better error message instead of traceback
