### ISSUE TITLE
Error on check_mx using verbose output

### ISSUE THREAD

**Issue by y0va** [modoboa/modoboa#1699]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes, on install, no on upgrade
* Webserver: Nginx

# Steps to reproduce

Execute `check_mx` with verbosity levels:

`python manage.py modo -v 3  check_mx`

# Current behavior
```
$ python manage.py modo -v 3  check_mx
/srv/modoboa/env/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/subcommand/base.py", line 53, in run_from_argv
    return super(SubcommandCommand, self).run_from_argv(argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/subcommand/base.py", line 80, in handle
    command = command_class(**command_class_kwargs)
TypeError: 'NoneType' object is not callable
```

`python manage.py modo check_mx`

Runs without error.

# Expected behavior

I see what happens when running `python manage.py modo -v 3 mx_check`.

**Comment by cremesk** [comment]
Some here.
Is a know Issue: [1664](https://github.com/modoboa/modoboa/issues/1664)

**Comment by y0va** [comment]
No. As I wrote `python manage.py modo check_mx`completes **without** error on my system. It only fails if I pass the `-v 3` switch.

**Comment by cremesk** [comment]
Okay thanks, good to know.

**Comment by gianks** [comment]
Using --traceback causes the same problem here with modoboa 1.14.0

**Comment by tonioo** [comment]
I think it's a python2 compat issue. It should be fixed now support has been dropped for this version.
