### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Th0rGer** [modoboa/modoboa#1710]
# Impacted versions

* Modoboa: i think 1.12.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Dont know/ Maybe a upgrade ? 

# Current behavior
on web page: 
Internal Server Error

# Expected behavior
?

# Traceback

> `Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/instance/instance/settings.py", line 331, in <module>
    from modoboa_amavis import settings as modoboa_amavis_settings
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_amavis/__init__.py", line 7, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 74, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.`

**Comment by tonioo** [comment]
@Th0rGer Try to upgrade your installation to the latest version please.

**Comment by Th0rGer** [comment]
I have.. works fine now. Only that i cant allow spam mails from the qarantane to gow through.

**Comment by tonioo** [comment]
@Th0rGer Do you have more information?

**Comment by Th0rGer** [comment]
When i want to accept a mail to go out from qarantane it says "undefined" when i press the button. Which information i can give you?
