### ISSUE TITLE
Some issues during Auto-installation

### ISSUE THREAD

**Issue by fresH229a** [modoboa/modoboa#1730]
# Impacted versions

* Modoboa: 1.13.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Reinstall on Debian 9.9
```

Executing: /lib/systemd/systemd-sysv-install enable postfix
● postfix.service - Postfix Mail Transport Agent
   Loaded: loaded (/lib/systemd/system/postfix.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Thu 2019-05-02 17:42:32 UTC; 1min 27s ago
```

```
Installing setuptools, pkg_resources, pip, wheel...done.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages (19.1)
Requirement already up-to-date: setuptools in ./env/lib/python2.7/site-packages (41.0.1)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```

```
Running setup.py install for Pillow ... error
    ERROR: Complete output from command /srv/modoboa/env/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-1cmQhh/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-NRnJP5/install-record.txt --single-version-externally-managed --compile --install-headers /srv/modoboa/env/include/site/python2.7/Pillow:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/__init__.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/_util.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/Image.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/features.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/_version.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/_binary.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing top-level names to src/Pillow.egg-info/top_level.txt
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1cmQhh/Pillow/setup.py", line 804, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html


    ----------------------------------------
ERROR: Command "/srv/modoboa/env/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-1cmQhh/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-NRnJP5/install-record.txt --single-version-externally-managed --compile --install-headers /srv/modoboa/env/include/site/python2.7/Pillow" failed with error code 1 in /tmp/pip-install-1cmQhh/Pillow/
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting rrdtool
```

Modoboa installation runs through, and modoboa is working but what are those errors o.O

**Comment by fresH229a** [comment]
I have ran now those 3 commands before the Modoboa Install:

```
apt-get install python3-dev python3-setuptools

apt-get install python-pip 
pip install Pillow
```

Still the same issue during installation

**Comment by mertowitch** [comment]
Use Centos 7.
Ubuntu not good for web and mail server.

**Comment by fresH229a** [comment]
@mertowitch I use Debian, not Ubuntu

**Comment by mertowitch** [comment]
Debian=Ubuntu
what is differences?

**Comment by fresH229a** [comment]
Ubuntu is based on Debian, it is not Debian at all but that is not the question here....

**Comment by tonioo** [comment]
@fresH229a Can you try to install the zlib1g-dev package and restart the installer?

**Comment by fresH229a** [comment]
I solved it by doing those 3 actions before Modoboa installation:

apt-get install python3-dev python3-setuptools libjpeg8-dev python-virtualenv python-pip
apt-get install python-pip 
pip install --upgrade --force-reinstall Pillow

All is fine now :)
