### ISSUE TITLE
Missing directory /srv/modoboa in Centos7

### ISSUE THREAD

**Issue by czarli22** [modoboa/modoboa#1752]
# Impacted versions

* Modoboa: latest
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
I have installed modoboa using installer sudo ./run.py --interactive domain.com
Then I remove by mistake the directory /srv/modoboa
I wanted to reinstall the modoboa server one more time
The user modoboa has been removed as well.

# Current behavior
The exception occurs:
`Traceback (most recent call last):
  File "./run.py", line 136, in <module>
    main(sys.argv[1:])
  File "./run.py", line 120, in main
    scripts.install("modoboa", config, args.upgrade)
  File "/tmp/modoboa-installer/modoboa_installer/scripts/__init__.py", line 22, in install
    getattr(script, appname.capitalize())(config, upgrade).run()
  File "/tmp/modoboa-installer/modoboa_installer/scripts/base.py", line 151, in run
    self.post_run()
  File "/tmp/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 247, in post_run
    self._deploy_instance()
  File "/tmp/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 159, in _deploy_instance
    sudo_user=self.user, cwd=self.home_dir)
  File "/tmp/modoboa-installer/modoboa_installer/utils.py", line 68, in exec_cmd
    process = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/srv/modoboa'
`

# Expected behavior
I do not know how to recreate the missing directory /srv/modoboa to finish the installation.

**Comment by czarli22** [comment]
I have init the VPS one more time to have fresh installation.
