### ISSUE TITLE
Modoboa HTTP Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by horvan** [modoboa/modoboa#1765]
# Impacted versions

* Modoboa: 1.14.0

* installer used: Yes 
* Webserver: Nginx

# Steps to reproduce
Install by useing modoboa installer
set up wit dns info on domain 

# Current behavior

Modoboa spwns error mails to root regaring to api See details

'
 **From: root@mail.huetervontamriel.de (Cron Daemon)
To: root@mail.huetervontamriel.de
Subject: Cron <root@vmd41117>    $PYTHON $INSTANCE/manage.py communicate_with_public_api
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <PYTHON=/srv/modoboa/env/bin/python>
X-Cron-Env: <INSTANCE=/srv/modoboa/instance>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
Message-Id: <20190802150008.60ECA1181C9D@mail.huetervontamriel.de>
Date: Fri,  2 Aug 2019 17:00:08 +0200 (CEST)

Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/management/commands/communicate_with_public_api.py", line 54, in handle
    self.client.update_instance(local_config.api_pk, data)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/api_client.py", line 71, in update_instance
    response.raise_for_status()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.modoboa.org/1/instances/11884/
**
'
# Expected behavior
No error expected
# Video/Screenshot link (optional)

**Comment by NineSeven8** [comment]
This is exactly the same issue I reported in 
Modoboa on U18.04 LTS issues after update #1751

If you are fresh installing on Ubuntu, just go for another mail solution, this is not being addressed at all.

**Comment by ihmc3jn09hk** [comment]
> 502 Server Error: Bad Gateway for url: https://api.modoboa.org/1/instances/11884/

Why the api call to modoboa's demo server ?

**Comment by tonioo** [comment]
To report statistics about the instance. You can disable this behaviour from the admin panel.
