### ISSUE TITLE
Phyton Install Problem

### ISSUE THREAD

**Issue by codiergott** [modoboa/modoboa#1817]
# Impacted versions

* Modoboa: BRAND NEW
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
I downloaded the installer and I get the following error when I run it.

Traceback (most recent call last):
  File "./run.py", line 13, in <module>
    from modoboa_installer import package
  File "/home/codiergott/modoboa-installer/modoboa_installer/package.py", line 105, in <module>
    backend = get_backend()
  File "/home/codiergott/modoboa-installer/modoboa_installer/package.py", line 93, in get_backend
    distname = utils.dist_name()
  File "/home/codiergott/modoboa-installer/modoboa_installer/utils.py", line 79, in dist_name
    name, version, _id = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

I use ArchLinux and Python 3.8.1.

**Comment by tonioo** [comment]
@codiergott Can you please move this issue to the https://github.com/modoboa/modoboa-installer repository please?
