### ISSUE TITLE
Installation stuck on "Running setup.py install for lxml"

### ISSUE THREAD

**Issue by bpincaro** [modoboa/modoboa#1832]
# Impacted versions

* Modoboa: latest
* installer used: Yes
* Webserver: Nginx/Apache

# Steps to reproduce
Followed the steps from the documentation's Recommended way (modoboa installer)
# Current behavior
All components are installed until lxml and modoboa where the installation gets stuck .

Using the command `sudo ./run.py --interactive --debug mysite.com`
I noticed the installation gets stuck on for a while and then the following error is thrown
```
Installing collected packages: lxml, modoboa
    Running setup.py install for lxml ... error
    ERROR: Command errored out with exit status 1:
     command: /srv/modoboa/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uqn5s_qx/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uqn5s_qx/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-h7g0yd5b/install-record.txt --single-version-externally-managed --compile --install-headers /srv/modoboa/env/include/site/python3.6/lxml
         cwd: /tmp/pip-install-uqn5s_qx/lxml/
    Complete output (86 lines):
    Building lxml version 4.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.29
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/__init__.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/sax.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/builder.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.6/lxml
    creating build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-3.6/lxml/includes
    creating build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.6/lxml/html
    creating build/lib.linux-x86_64-3.6/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-3.6/lxml/isoschematron
    copying src/lxml/etree.h -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/etree_api.h -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/__init__.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.6/lxml/includes
    creating build/lib.linux-x86_64-3.6/lxml/isoschematron/resources
    creating build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/rng
    creating build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl
    creating build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1      running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/lxml
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/srv/modoboa/env/include -I/usr/include/python3.6m -c src/lxml/etree.c -o build/temp.linux-x86_64-3.6/src/lxml/etree.o -w
    virtual memory exhausted: Cannot allocate memory
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    creating tmp
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInit46eu0oev.c -o tmp/xmlXPathInit46eu0oev.o
    /tmp/xmlXPathInit46eu0oev.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^~~~
    cc tmp/xmlXPathInit46eu0oev.o -lxml2 -o a.out
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /srv/modoboa/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uqn5s_qx/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uqn5s_qx/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-h7g0yd5b/install-record.txt --single-version-externally-managed --compile --install-headers /srv/modoboa/env/include/site/python3.6/lxml Check the logs for full command output.
Collecting rrdtool
  Using cached rrdtool-0.1.15.tar.gz (21 kB)
Collecting modoboa-amavis
  Using cached modoboa_amavis-1.2.3-py2.py3-none-any.whl (186 kB)
Collecting modoboa-pdfcredentials
  Using cached modoboa_pdfcredentials-1.3.2-py2.py3-none-any.whl (68 kB)
Collecting modoboa-postfix-autoreply
  Using cached modoboa_postfix_autoreply-1.5.1-py2.py3-none-any.whl (86 kB)
Collecting modoboa-sievefilters
  Using cached modoboa_sievefilters-1.4.2-py2.py3-none-any.whl (120 kB)
Collecting modoboa-stats
  Using cached modoboa_stats-1.4.1-py2.py3-none-any.whl (110 kB)
Collecting modoboa-webmail
  Using cached modoboa_webmail-1.5.0-py2.py3-none-any.whl (196 kB)
Collecting modoboa-contacts
  Using cached modoboa_contacts-0.7.3-py2.py3-none-any.whl (666 kB)
Collecting modoboa-radicale
  Using cached modoboa_radicale-1.3.6-py2.py3-none-any.whl (1.8 MB)
Collecting mysqlclient
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
    ERROR: Command errored out with exit status 1:
     command: /srv/modoboa/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q_83vrbb/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q_83vrbb/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-q_83vrbb/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-q_83vrbb/mysqlclient/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q_83vrbb/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-q_83vrbb/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-q_83vrbb/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
bash: modoboa-admin.py: command not found
None
```
This is my server config:
Processor: 1 vCore
RAM: 2 GiB
Storage: 20 GiB
OS: Ubuntu Server 18.04 LTS

Any ideas ?

**Comment by bpincaro** [comment]
Ok, got an update... after a while the following error was shownd:

```
Installing collected packages: lxml, modoboa
    Running setup.py install for lxml ... error
    ERROR: Command errored out with exit status 1:
     command: /srv/modoboa/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uqn5s_qx/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uqn5s_qx/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-h7g0yd5b/install-record.txt --single-version-externally-managed --compile --install-headers /srv/modoboa/env/include/site/python3.6/lxml
         cwd: /tmp/pip-install-uqn5s_qx/lxml/
    Complete output (86 lines):
    Building lxml version 4.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.29
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/__init__.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/sax.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/builder.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.6/lxml
    creating build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-3.6/lxml/includes
    creating build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.6/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.6/lxml/html
    creating build/lib.linux-x86_64-3.6/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-3.6/lxml/isoschematron
    copying src/lxml/etree.h -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/etree_api.h -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.6/lxml
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/__init__.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.6/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.6/lxml/includes
    creating build/lib.linux-x86_64-3.6/lxml/isoschematron/resources
    creating build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/rng
    creating build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl
    creating build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1      running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/lxml
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/srv/modoboa/env/include -I/usr/include/python3.6m -c src/lxml/etree.c -o build/temp.linux-x86_64-3.6/src/lxml/etree.o -w
    virtual memory exhausted: Cannot allocate memory
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    creating tmp
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInit46eu0oev.c -o tmp/xmlXPathInit46eu0oev.o
    /tmp/xmlXPathInit46eu0oev.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^~~~
    cc tmp/xmlXPathInit46eu0oev.o -lxml2 -o a.out
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /srv/modoboa/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uqn5s_qx/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uqn5s_qx/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-h7g0yd5b/install-record.txt --single-version-externally-managed --compile --install-headers /srv/modoboa/env/include/site/python3.6/lxml Check the logs for full command output.
Collecting rrdtool
  Using cached rrdtool-0.1.15.tar.gz (21 kB)
Collecting modoboa-amavis
  Using cached modoboa_amavis-1.2.3-py2.py3-none-any.whl (186 kB)
Collecting modoboa-pdfcredentials
  Using cached modoboa_pdfcredentials-1.3.2-py2.py3-none-any.whl (68 kB)
Collecting modoboa-postfix-autoreply
  Using cached modoboa_postfix_autoreply-1.5.1-py2.py3-none-any.whl (86 kB)
Collecting modoboa-sievefilters
  Using cached modoboa_sievefilters-1.4.2-py2.py3-none-any.whl (120 kB)
Collecting modoboa-stats
  Using cached modoboa_stats-1.4.1-py2.py3-none-any.whl (110 kB)
Collecting modoboa-webmail
  Using cached modoboa_webmail-1.5.0-py2.py3-none-any.whl (196 kB)
Collecting modoboa-contacts
  Using cached modoboa_contacts-0.7.3-py2.py3-none-any.whl (666 kB)
Collecting modoboa-radicale
  Using cached modoboa_radicale-1.3.6-py2.py3-none-any.whl (1.8 MB)
Collecting mysqlclient
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
    ERROR: Command errored out with exit status 1:
     command: /srv/modoboa/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q_83vrbb/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q_83vrbb/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-q_83vrbb/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-q_83vrbb/mysqlclient/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q_83vrbb/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-q_83vrbb/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-q_83vrbb/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
bash: modoboa-admin.py: command not found
None
```

**Comment by bpincaro** [comment]
Created a swap file... Problem solved!

**Comment by widevel** [comment]
> Created a swap file... Problem solved!

Can you explain this? I am using ubuntu 20 and i have the same issue. Thanks

**Comment by bpincaro** [comment]
> > Created a swap file... Problem solved!
> 
> Can you explain this? I am using ubuntu 20 and i have the same issue. Thanks

https://itsfoss.com/create-swap-file-linux/#:~:text=A%20swap%20file%20allows%20Linux,the%20data%20from%20the%20disk.

Take a look... I think it's very well explained!
