### ISSUE TITLE
Error 500 after Update

### ISSUE THREAD

**Issue by kev1904** [modoboa/modoboa#1841]
# Impacted versions

* Modoboa: update to 1.14.0 from 1.13
* installer used: Yes
* Webserver: Nginx

# Video/Screenshot link (optional)
`Traceback (most recent call last):
  File "./instance/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./instance/settings.py", line 355, in <module>
    DNSBL_PROVIDERS.remove("bad.psky.me")
ValueError: list.remove(x): x not in list
Mon Feb 17 15:50:16 2020 - unable to load app 0 (mountpoint='') (callable not found or import error)
`

**Comment by kev1904** [comment]
Solved by my self, commented out
#DNSBL_PROVIDERS.remove("bad.psky.me")
in the settingy.py
