### ISSUE TITLE
from progressbar.compat import * ImportError: No module named compat ```

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa#1865]
# Impacted versions

* Modoboa: 1.1.14
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
view root email on modoboa server

hi, I am debugging a problem and i accidentally discovered that these emails were piling up in the root mailbox on the modoboa server.  there are a lot and increasing rapidly.
Please help in determining why they are being created.

thanks

```From root@mail2.fujifilmusa.com  Thu Apr  2 09:00:07 2020
Return-Path: <root@mail2.fujifilmusa.com>
X-Original-To: root
Delivered-To: root@mail2.fujifilmusa.com
Received: by mail2.fujifilmusa.com (Postfix, from userid 0)
        id 7915360A4D39; Thu,  2 Apr 2020 13:00:07 +0000 (UTC)
From: "(Cron Daemon)" <root@mail2.fujifilmusa.com>
To: root@mail2.fujifilmusa.com
Subject: Cron <root@ffcplmail>    $PYTHON $INSTANCE/manage.py modo check_mx
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=11743>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <PYTHON=/srv/modoboa/env/bin/python>
X-Cron-Env: <INSTANCE=/srv/modoboa/instance>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20200402130007.7915360A4D39@mail2.fujifilmusa.com>
Date: Thu,  2 Apr 2020 13:00:07 +0000 (UTC)

Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa/admin/management/commands/modo.py", line 10, in <module>
    from .subcommands._import import ImportCommand
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_import.py", line 10, in <module>
    import progressbar
  File "/srv/modoboa/env/lib/python2.7/site-packages/progressbar/__init__.py", line 58, in <module>
    from progressbar.compat import *
ImportError: No module named compat
```

**Comment by tonyguadagno** [comment]
fyi, i just looked further and realized that there is a mailbox called 'opendkim' that also has these in them.  currently, that mailbox is 10meg large.

thanks

**Comment by tonioo** [comment]
@tonyguadagno can you load the virtualenv and run the following command please:
```
pip list
```

**Comment by tonyguadagno** [comment]
```# pip list
backports.ssl-match-hostname (3.5.0.1)
blivet (0.61.15.74)
Brlapi (0.6.0)
chardet (2.2.1)
configobj (4.7.2)
coverage (3.6b3)
cupshelpers (1.0)
decorator (3.4.0)
di (0.3)
ethtool (0.8)
firstboot (19.5)
fros (1.0)
futures (3.1.1)
iniparse (0.4)
initial-setup (0.3.9.44)
ipaddress (1.0.16)
IPy (0.75)
javapackages (1.0.0)
kitchen (1.1.1)
langtable (0.0.31)
lxml (3.2.1)
meld3 (0.6.10)
ntplib (0.3.2)
perf (0.1)
pip (8.1.2)
policycoreutils-default-encoding (0.1)
pycups (1.9.63)
pycurl (7.19.0)
pygobject (3.22.0)
pygpgme (0.3)
pyinotify (0.9.4)
pykickstart (1.99.66.21)
pyliblzma (0.5.3)
pyparsing (1.5.6)
pyparted (3.9)
pysmbc (1.0.13)
python-augeas (0.5.0)
python-linux-procfs (0.4.9)
python-meh (0.25.3)
python-nss (0.16.0)
pytz (2016.10)
pyudev (0.15)
pyxattr (0.5.1)
PyYAML (3.10)
schedutils (0.4)
seobject (0.1)
sepolicy (1.1)
setroubleshoot (1.1)
setuptools (0.9.8)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
SSSDConfig (1.16.4)
subprocess32 (3.2.6)
supervisor (3.4.0)
urlgrabber (3.10)
virtualenv (15.1.0)
yum-langpacks (0.4.2)
yum-metadata-parser (1.1.4)
You are using pip version 8.1.2, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by tonioo** [comment]
@tonyguadagno I don't think it's the virtualenv used by Modoboa. You should load the one located at /srv/modoboa/env.

**Comment by tonyguadagno** [comment]
sorry, my mistake

```
(env) -bash-4.2$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
backports.csv (1.0.7)
bcrypt (3.1.4)
caldav (0.6.2)
certifi (2020.4.5.1)
cffi (1.14.0)
chardet (3.0.4)
click (7.1.1)
coreapi (2.3.3)
coreapi-cli (1.0.6)
coreschema (0.0.4)
cryptography (2.9)
dj-database-url (0.5.0)
Django (1.11.29)
django-braces (1.11.0)
django-ckeditor (5.2.2)
django-filter (1.1.0)
django-reversion (2.0.12)
django-subcommand2 (0.1.1)
django-webpack-loader (0.7.0)
django-xforwardedfor-middleware (2.0)
djangorestframework (3.7.3)
dnspython (1.15.0)
drf-nested-routers (0.91)
enum34 (1.1.10)
feedparser (5.2.1)
future (0.18.2)
gevent (1.4.0)
greenlet (0.4.15)
html2text (2019.8.11)
idna (2.9)
ipaddress (1.0.23)
itypes (1.1.0)
Jinja2 (2.11.1)
jsonfield (2.0.2)
LEPL (5.1.3)
lxml (4.5.0)
MarkupSafe (1.1.1)
modoboa (1.14.0)
modoboa-amavis (1.2.3)
modoboa-contacts (0.7.3)
modoboa-pdfcredentials (1.3.2)
modoboa-postfix-autoreply (1.5.1)
modoboa-radicale (1.3.6)
modoboa-sievefilters (1.4.2)
modoboa-stats (1.4.1)
modoboa-webmail (1.5.0)
passlib (1.7.1)
Pillow (6.2.2)
pip (20.0.2)
progressbar33 (2.4)
psycopg2 (2.8.5)
py-dateutil (2.2)
pycparser (2.20)
python-dateutil (2.8.1)
pytz (2019.3)
reportlab (3.5.42)
requests (2.23.0)
rfc6266 (0.0.4)
rrdtool (0.1.15)
setuptools (28.8.0)
sievelib (1.1.1)
six (1.14.0)
tzlocal (2.0.0)
uritemplate (3.0.1)
urllib3 (1.25.8)
vobject (0.9.6.1)
wheel (0.29.0)
```

**Comment by tonioo** [comment]
@tonyguadagno Have you tried an upgrade to 1.15 ?
