### ISSUE TITLE
autoreply broke

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa#1866]
# Impacted versions

* Modoboa: 1.1.14
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
configure autoreply for a user

# Current behavior
no autoreply is sent, see error below

# Expected behavior

# Video/Screenshot link (optional)
![image](https://user-images.githubusercontent.com/25204879/78264595-5c13a680-74d1-11ea-8385-62b994f1494f.png)

```
Apr  2 10:58:00 ffcplmail postfix/smtpd[24756]: proxy-accept: END-OF-MESSAGE: 250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 2A9BB6090F44; from=<tguadagno.contractor@fujifilm.com> to=<questions@studentsofstorytelling.com> proto=ESMTP helo=<mail-qk1-f181.google.com>
Apr  2 10:58:00 ffcplmail pipe[25979]: fatal: pipe_command: execvp /srv/modoboa/env/bin/python: Permission denied
Apr  2 10:58:00 ffcplmail postfix/pipe[24772]: 2A9BB6090F44: to=<questions@studentsofstorytelling.com@autoreply.studentsofstorytelling.com>, orig_to=<questions@studentsofstorytelling.com>, relay=autoreply, delay=0.11, delays=0.09/0.01/0/0.01, dsn=4.3.0, status=deferred (temporary failure. Command output: pipe: fatal: pipe_command: execvp /srv/modoboa/env/bin/python: Permission denied )
````

**Comment by tonyguadagno** [comment]
after a lot of searching, i can see now this is an selinux issue:
```
type=AVC msg=audit(1586185412.500:22332): avc:  denied  { execute_no_trans } for  pid=4746 comm="pipe" path="/srv/modoboa/env/bin/python" dev="dm-0" ino=1347866 scontext=system_u:system_r:postfix_pipe_t:s0 tcontext=unconfined_u:object_r:httpd_sys_content_t:s0 tclass=file permissive=0
type=SYSCALL msg=audit(1586185412.500:22332): arch=c000003e syscall=59 success=no exit=-13 a0=55c494c882c0 a1=55c494c8d0d0 a2=55c494c88460 a3=0 items=0 ppid=4460 pid=4746 auid=4294967295 uid=1003 gid=1003 euid=1003 suid=1003 fsuid=1003 egid=1003 sgid=1003 fsgid=1003 tty=(none) ses=4294967295 comm="pipe" exe="/usr/libexec/postfix/pipe" subj=system_u:system_r:postfix_pipe_t:s0 key=(null)
type=PROCTITLE msg=audit(1586185412.500:22332): proctitle=70697065002D6E006175746F7265706C79002D7400756E697800666C6167733D00757365723D766D61696C00766D61696C00617267763D2F7372762F6D6F646F626F612F656E762F62696E2F707974686F6E002F7372762F6D6F646F626F612F696E7374616E63652F6D616E6167652E7079006175746F7265706C7900247365
```
but i don't know how to fix it.  i use this but it does not help.....can anyone point me in the right direction?
```
ausearch -c 'pipe' --raw | audit2allow -M my-pipe
semodule -i my-pipe.pp
```

**Comment by tonyguadagno** [comment]
so, although i don't want to, for troubleshooting, i disabled selinux.  when i did that, the permission denied went away, but i go this instead
```
<"questions@studentsofstorytelling.com"@autoreply.studentsofstorytelling.com>
    (expanded from <questions@studentsofstorytelling.com>): Command died with
    status 1: "/srv/modoboa/env/bin/python". Command output: Traceback (most
    recent call last):   File "/srv/modoboa/instance/manage.py", line 22, in
    <module>     execute_from_command_line(sys.argv)   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 364, in execute_from_command_line     utility.execute()   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py",
    line 283, in run_from_argv     self.execute(*args, **cmd_options)   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py",
    line 330, in execute     output = self.handle(*args, **options)   File
    "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py",
    line 216, in handle     send_autoreply(sender, mbox, armessage,
    original_msg)   File
    "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py",
    line 109, in send_autoreply     msg.send()   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/mail/message.py",
    line 348, in send     return
    self.get_connection(fail_silently).send_messages([self])   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/mail/backends/smtp.py",
    line 104, in send_messages     new_conn_created = self.open()   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/mail/backends/smtp.py",
    line 64, in open     self.connection = self.connection_class(self.host,
    self.port, **connection_params)   File "/usr/lib64/python2.7/smtplib.py",
    line 255, in __init__     (code, msg) = self.connect(host, port)   File
    "/usr/lib64/python2.7/smtplib.py", line 315, in connect     self.sock =
    self._get_socket(host, port, self.timeout)   File
    "/usr/lib64/python2.7/smtplib.py", line 290, in _get_socket     return
    socket.create_connection((host, port), timeout)   File
    "/usr/lib64/python2.7/socket.py", line 571, in create_connection     raise
    err socket.error: [Errno 111] Connection refused
```
it would be helpful to know what it was trying to connect to

**Comment by tonioo** [comment]
@tonyguadagno It's trying to connect to local SMTP server. Can you check you have one running on localhost?

**Comment by tonyguadagno** [comment]
[root@ffcplmail /]# netstat -na |grep :25
tcp        0      0 172.19.5.13:25          0.0.0.0:*               LISTEN
tcp        0      0 172.19.5.13:25          172.19.4.120:34320      TIME_WAIT
tcp        0      0 172.19.5.13:25          172.19.4.120:34324      TIME_WAIT
tcp        0      0 172.19.5.13:25          172.19.4.120:34316      TIME_WAIT
tcp        0      0 172.19.5.13:25          172.19.4.120:34312      TIME_WAIT
[root@ffcplmail /]# netstat -na |grep :587
tcp        0      0 172.19.5.13:587         0.0.0.0:*               LISTEN
tcp        0      0 172.19.4.123:58718      172.19.4.100:3268       ESTABLISHED

**Comment by tonioo** [comment]
@tonyguadagno can you check mail logs to see if there's any error?

**Comment by tonyguadagno** [comment]
yes, these

```
Apr  6 14:41:11 ffcplmail dovecot: lmtp(22922): Disconnect from local: Successful quit
Apr  6 14:41:11 ffcplmail postfix/lmtp[22921]: D3DDB61CF9F4: to=<questions@studentsofstorytelling.com>, relay=mail2.fujifilmusa.com[private/dovecot-lmtp], delay=0.17, delays=0.09/0.01/0.02/0.06, dsn=2.0.0, status=sent (250 2.0.0 <questions@studentsofstorytelling.com> qBi/OcZ3i16KWQAAmxVUdg Saved)
Apr  6 14:41:12 ffcplmail postfix/pipe[22920]: D3DDB61CF9F4: to=<questions@studentsofstorytelling.com@autoreply.studentsofstorytelling.com>, orig_to=<questions@studentsofstorytelling.com>, relay=autoreply, delay=2.1, delays=0.09/0.01/0/2, dsn=5.3.0, status=bounced (Command died with status 1: "/srv/modoboa/env/bin/python". Command output: Traceback (most recent call last):   File "/srv/modoboa/instance/manage.py", line 22, in <module>     execute_from_command_line(sys.argv)   File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line     utility.execute()   File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute     self.fetch_command(subcommand).run_from_argv(self.argv)   File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv     self.execute(*args, **cmd_options)   File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute     output = self.handle(*args, **options)   File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py", line 216, in handle     send_autoreply(sender, mbox, armessage, original_msg)   File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py", line 109, in send_autoreply     msg.send()   File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/mail/message.py", line 348, in send     return self.get_connection(fail_silently).send_messages([self])   File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages     new_conn_created = self.open()   File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 64, in open     self.connection = self.connection_class(self.host, self.port, **connection_params)   File "/usr/lib64/python2.7/smtplib.py", line 255, in __init__     (code, msg) =
Apr  6 14:41:12 ffcplmail postfix/cleanup[22918]: E769B61CF9F5: message-id=<20200406184112.E769B61CF9F5@mail2.fujifilmusa.com>
Apr  6 14:41:12 ffcplmail postfix/qmgr[8757]: E769B61CF9F5: from=<>, size=14425, nrcpt=1 (queue active)
Apr  6 14:41:12 ffcplmail postfix/bounce[22973]: D3DDB61CF9F4: sender non-delivery notification: E769B61CF9F5
Apr  6 14:41:12 ffcplmail postfix/qmgr[8757]: D3DDB61CF9F4: removed
```

**Comment by tonioo** [comment]
@tonyguadagno that's the same error...

**Comment by tonyguadagno** [comment]
yes, i am looking at /var/log/maillog.....should i be looking somewhere else?

**Comment by tonioo** [comment]
No that's the right place but the error is the same than the one you received by email. I'd like to know why the connection is refused... Can you try to connect on localhost port 25 using python or anything you know to see if you get the same behaviour?

**Comment by tonyguadagno** [comment]
thanks for pointing me in the right direction!!!  I figured out that i was only bound to a vip
/etc/postfix/main.cf
```
inet_interfaces = 172.19.5.13
```
i changed it to
```
inet_interfaces = 172.19.5.13,127.0.0.1
```
and auto reply works.  thanks again!
