### ISSUE TITLE
Modoboa :  rrdtool.OperationalError: /srv/modoboa/rrdfiles/new_accounts.rrd: illegal attempt to update using time 1589302800 when last update time is 1589313600 (minimum one second step)

### ISSUE THREAD

**Issue by xeeshan-Mustafa** [modoboa/modoboa#1963]
# Impacted versions

* Modoboa: X.X.x
* installer used: Yes/No ?
* Webserver: Nginx/Apache

# Steps to reproduce

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by ddiguru** [comment]
I'm also receiving this.

I just upgraded to 1.15.0 and rebuilt my venv. This is on CentOS 7.x

```
Traceback (most recent call last):
 File "/srv/modoboa/instance/manage.py", line 21, in <module>
   main()
 File "/srv/modoboa/instance/manage.py", line 17, in main
   execute_from_command_line(sys.argv)
 File "/srv/modoboa/env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
   utility.execute()
 File "/srv/modoboa/env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/srv/modoboa/env/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
   self.execute(*args, **cmd_options)
 File "/srv/modoboa/env/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
   output = self.handle(*args, **options)
 File "/srv/modoboa/env/lib64/python3.6/site-packages/modoboa_stats/management/commands/update_statistics.py", line 84, in handle
   self.update_account_creation_stats(options["rebuild"])
 File "/srv/modoboa/env/lib64/python3.6/site-packages/modoboa_stats/management/commands/update_statistics.py", line 79, in update_account_creation_stats
   rrdtool.update(str(db_path), *data)
rrdtool.OperationalError: /srv/modoboa/rrdfiles/new_accounts.rrd: illegal attempt to update using time 1589720400 when last update time is 1589720400 (minimum one second step)

```
While i'm not 100% - i temporarily commented out the following line in my crontab:

```
#0       *       *       *       *       root    $PYTHON $INSTANCE/manage.py update_statistics
```

I did this simply to stop the email warnings from filling the inbox. I'd like to fig. out a more permanent fix. Is this the code or perhaps an upgraded/updated rrdtool?
