### ISSUE TITLE
pip install mysqlclient - fail

### ISSUE THREAD

**Issue by DevDorrejo** [modoboa/modoboa#1978]
# Impacted versions
* OS: Opensuse Tumbleweed
* Python version: 3.8.3 
* Modoboa: N/A
* installer used: No
* Webserver: Apache

# Steps to reproduce
pip install mysqlclient
# Current behavior

```
ERROR: Command errored out with exit status 1:
command: /home/modoboa/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rx88fa31/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rx88fa31/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mw58a5v4
cwd: /tmp/pip-install-rx88fa31/mysqlclient/
Complete output (12 lines):
/bin/sh: mysql_config: orden no encontrada
/bin/sh: mariadb_config: orden no encontrada
/bin/sh: mysql_config: orden no encontrada
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-rx88fa31/mysqlclient/setup.py", line 16, in <module>
metadata, options = get_config()
File "/tmp/pip-install-rx88fa31/mysqlclient/setup_posix.py", line 61, in get_config
libs = mysql_config("libs")
File "/tmp/pip-install-rx88fa31/mysqlclient/setup_posix.py", line 29, in mysql_config
raise EnvironmentError("%s not found" % (_mysql_config_path,))
OSError: mysql_config not found
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

# Expected behavior
install successful 
# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@DevDorrejo You need to install mysql development files.
