### ISSUE TITLE
pip freeze not working in my virtual env, instead it is showing this!

### ISSUE THREAD

**Issue by luciferon** [modoboa/modoboa#1986]
(chinu) abitribe@yashmacbook chinu % pip freeze
Traceback (most recent call last):
  File "/Users/abitribe/Desktop/chinu/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Users/abitribe/Desktop/chinu/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/Users/abitribe/Desktop/chinu/lib/python2.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
    module = importlib.import_module(module_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/abitribe/Desktop/chinu/lib/python2.7/site-packages/pip/_internal/commands/freeze.py", line 12, in <module>
    from pip._internal.operations.freeze import freeze
  File "/Users/abitribe/Desktop/chinu/lib/python2.7/site-packages/pip/_internal/operations/freeze.py", line 16, in <module>
    from pip._internal.req.constructors import (
  File "/Users/abitribe/Desktop/chinu/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 12, in <module>
    from .req_install import InstallRequirement
  File "/Users/abitribe/Desktop/chinu/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 30, in <module>
    from pip._internal.operations.install.wheel import install_wheel
  File "/Users/abitribe/Desktop/chinu/lib/python2.7/site-packages/pip/_internal/operations/install/wheel.py", line 25, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/Users/abitribe/Desktop/chinu/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
ImportError: No module named compat

**Comment by tonioo** [comment]
@luciferon Have you updated pip?

**Comment by luciferon** [comment]
Yes i have !

**Comment by luciferon** [comment]
By the way the answer was simple, we have to create a virtualenv using
" virtualenv -p python3 "
this will create a virtaulenv with python3 as default python and hence the code will run!

**Comment by luciferon** [comment]
> @luciferon Have you updated pip?

yes I have!
