### ISSUE TITLE
Can't add users

### ISSUE THREAD

**Issue by malteneu** [modoboa/modoboa#2076]
# Impacted versions

* Modoboa: 1.15.0
* installer used: Yes
* Webserver: Nginx

Used the installer to install modoba. Wasn't able to add users. Running `python3 manage.py migrate` gave me this error:

`Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 343, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 232, in close_all
    for alias in self:
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 226, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/modoboa/instance/instance/settings.py", line 334, in <module>
    from modoboa_amavis import settings as modoboa_amavis_settings
ModuleNotFoundError: No module named 'modoboa_amavis'`

Never changed anything.

**Comment by tonioo** [comment]
@malteneu The trace you pasted indicates you've not loaded the virtual environment used by Modoboa. Can you retry with the virtualenv enabled?

**Comment by malteneu** [comment]
Running in migrate in in the virtual enviroment throws this back:

`Traceback (most recent call last):
  File "manage.py", line 10, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 16, in main
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?`

**Comment by tonioo** [comment]
@malteneu Are you sure you loaded the virtualenv? Can you paste the commands you used?
