### ISSUE TITLE
Problems with generate_postfix_maps

### ISSUE THREAD

**Issue by DaveDischord** [modoboa/modoboa#2077]
# Impacted versions

* OS Type: Debian/Ubuntu,
* OS Version: 18.04
* Database Type: PostgreSQL/MySQL
* Database version: X.y
* Modoboa:1.16.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
**python3 manage.py generate_postfix_maps --destdir /etc/postfix**
# Current behavior
```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/.local/lib/python3.6/site-packages/django/core/manageme_init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/.local/lib/python3.6/site-packages/django/core/manageme_init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/.local/lib/python3.6/site-packages/django/core/managemease.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/.local/lib/python3.6/site-packages/django/core/managemease.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/.local/lib/python3.6/site-packages/modoboa/core/managemcommands/generate_postfix_maps.py", line 160, in handle
    force_overwrite=options["force_overwrite"])
  File "/srv/modoboa/.local/lib/python3.6/site-packages/modoboa/core/managemcommands/generate_postfix_maps.py", line 142, in __render_map_file
    with open(fullpath, "w") as fp:
PermissionError: [Errno 13] Permission denied: '/etc/postfix/sql-domains.cf'
```
# Expected behavior
No Error
# Video/Screenshot link (optional)
A slew of issues started happening when I upgraded from 1.15 to 1.16 (using  ./run.py --upgrade).  Now emails aren't coming through and some people are unable to log in, via Webmail or Outlook.  I'm using LDAP auth through Active Directory

**Comment by bduhan** [comment]
You need to use root privileges when running this command.

**Comment by DaveDischord** [comment]
Still get the same error, even in root

**Comment by tonioo** [comment]
Make sure the /etc/postfix directory has write permission.

**Comment by DaveDischord** [comment]
Ended up changing owner of /etc/postfix to 'modoboa' from 'root'. Fixed this issue.
