### ISSUE TITLE
Exceptions during modo check_mx

### ISSUE THREAD

**Issue by mundschenk-at** [modoboa/modoboa#2081]
# Impacted versions

* OS Type: FreeBSD
* OS Version: 12.1-RELEASE-p10
* Database Type: MySQL
* Database version: 10.4.14-MariaDB
* Modoboa: 1.17.0
* installer used: No
* Webserver: Nginx

# Steps to reproduce
Run the command `modo check_mx`.

# Current behavior
```
Traceback (most recent call last):
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
modoboa.admin.models.alarm.DoesNotExist: Alarm matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.DataError: (1406, "Data too long for column 'title' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/libexec/modoboa/instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/modoboa/admin/management/commands/modo.py", line 50, in execute
    return options.pop('command').execute(*args, **options)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 296, in handle
    self.check_domain(domain, **options)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 219, in check_domain
    self.check_valid_mx(domain, mx_list, **options)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 189, in check_valid_mx
    ", ".join(mx_names))
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 674, in get_or_create
    return super(RelatedManager, self.db_manager(db)).get_or_create(**kwargs)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/query.py", line 541, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/query.py", line 575, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1375, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/libexec/modoboa/env/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'title' at row 1")
```

# Expected behavior
Successful completion of command.

**Comment by mundschenk-at** [comment]
This happens after updating to 1.17.0 from 1.15.0 (apparently after accidentally skipping 1.16.0). It appears related to this commit in [_mx.py](https://github.com/modoboa/modoboa/commit/08360400a9d9d8062a53d62b0630b2f527cf0f78#diff-aa493d9880d1fa3ce026ad7c8f962354e4adf15f5b2b933bea85912f7b15c4f6).

**Comment by tonioo** [comment]
Looks like the title field on the new alarm model is a bit small (150 characters)

**Comment by mundschenk-at** [comment]
> Looks like the title field on the new alarm model is a bit small (150 characters)

Any way to apply an interim fix (other than disabling the cron checks)?

**Comment by tonioo** [comment]
Maybe truncate the data before it is saved to the database?

**Comment by kokel** [comment]
Same Problem here:

`~$ /opt/venvs/modoboa/bin/python3 /opt/modoboa/svcustomers/manage.py modo check_mx
Traceback (most recent call last):
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
modoboa.admin.models.alarm.DoesNotExist: Alarm matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(150)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/modoboa/svcustomers/manage.py", line 21, in <module>
    main()
  File "/opt/modoboa/svcustomers/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/modoboa/admin/management/commands/modo.py", line 50, in execute
    return options.pop('command').execute(*args, **options)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 296, in handle
    self.check_domain(domain, **options)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 219, in check_domain
    self.check_valid_mx(domain, mx_list, **options)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 189, in check_valid_mx
    ", ".join(mx_names))
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 674, in get_or_create
    return super(RelatedManager, self.db_manager(db)).get_or_create(**kwargs)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/query.py", line 541, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/query.py", line 575, in _create_object_from_params
    obj = self.create(**params)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1375, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venvs/modoboa/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(150)`
