### ISSUE TITLE
url.port contains password instead of port number

### ISSUE THREAD

**Issue by NESC1US** [modoboa/modoboa#2131]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 20.04.1
* Database Type: PostgreSQL
* Database version: X.y
* Modoboa: todays master
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
sudo ./run.py perfugium.net --debug --interactive
fill up passwords
# Current behavior
instead of port number, the script used password.
```
Traceback (most recent call last):
  File "/srv/modoboa/env/bin/modoboa-admin.py", line 6, in <module>
    handle_command_line()
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa/core/commands/__init__.py", line 99, in handle_command_line
    commands[args.command](commands, verbose=args.verbose).run(remaining)
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa/core/commands/__init__.py", line 39, in run
    self.handle(args)
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa/core/commands/deploy.py", line 188, in handle
    info = dj_database_url.config(default=url)
  File "/srv/modoboa/env/lib/python3.8/site-packages/dj_database_url.py", line 55, in config
    config = parse(s, engine, conn_max_age, ssl_require)
  File "/srv/modoboa/env/lib/python3.8/site-packages/dj_database_url.py", line 105, in parse
    port = (str(url.port) if url.port and engine == SCHEMES['oracle']
  File "/usr/lib/python3.8/urllib/parse.py", line 174, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as '<content of Modoboa db password from --interactive --debug>'
None
```
# Expected behavior
installation working
# Video/Screenshot link (optional)

**Comment by kryskool** [comment]
Hi @NESC1US 

What is the shell you use ?

**Comment by NESC1US** [comment]
this is a freshly installed, fully upgraded, default ubuntu server 20.04.1 running as a virtual machine, bash is default there.

**Comment by kryskool** [comment]
Hi @NESC1US 

Do you have an @ in your password ?

Regards

**Comment by NESC1US** [comment]
sadly, i am unable to find my note with the passwords, but i doubt that any of the passwords contained @

**Comment by NESC1US** [comment]
@kryskool do you want me to reproduce this again? if so, what else you think you need to troubleshoot that?

**Comment by kryskool** [comment]
Hi @NESC1US 

Yes if you can retry, and indicate us if you use any special characters

regards
