### ISSUE TITLE
NGINX to Apache2

### ISSUE THREAD

**Issue by NA7KR** [modoboa/modoboa#2133]
# Impacted versions

* OS Type: Debian
* OS Version: Number Buster
* Database Type:  MySQL
* Database version: 10.3.27
* Modoboa: 1.17
* installer used: Yes
* Webserver: Nginx/Apache

# Switch from NGINX to Apache2 get this error, Have Python3.7.3  installed, What Can I do to fix this?

```

[Thu Jan 21 13:08:37.699216 2021] [ssl:debug] [pid 15677] ssl_engine_kernel.c(383): [client x.x.x.x:56290] AH02034: Initial (No.1) HTTPS request received for child 0 (server mail.test.org:443)
[Thu Jan 21 13:08:37.699561 2021] [authz_core:debug] [pid 15677] mod_authz_core.c(820): [client x.x.x.x:56290] AH01626: authorization result of Require all granted: granted
[Thu Jan 21 13:08:37.699571 2021] [authz_core:debug] [pid 15677] mod_authz_core.c(820): [client x.x.x.x:56290] AH01626: authorization result of <RequireAny>: granted
[Thu Jan 21 13:08:37.699713 2021] [authz_core:debug] [pid 15677] mod_authz_core.c(820): [client x.x.x.x:56290] AH01626: authorization result of Require all granted: granted
[Thu Jan 21 13:08:37.699721 2021] [authz_core:debug] [pid 15677] mod_authz_core.c(820): [client x.x.x.x:56290] AH01626: authorization result of <RequireAny>: granted
[Thu Jan 21 13:08:37.728803 2021] [wsgi:info] [pid 15677] [client x.x.x.x:56290] mod_wsgi (pid=15677, process='', application='mail.test.org|'): Loading Python script file '/srv/modoboa/instance/instance/wsgi.py'.
[Thu Jan 21 13:08:37.920838 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290] mod_wsgi (pid=15677): Failed to exec Python script file '/srv/modoboa/instance/instance/wsgi.py'.
[Thu Jan 21 13:08:37.920887 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290] mod_wsgi (pid=15677): Exception occurred processing WSGI script '/srv/modoboa/instance/instance/wsgi.py'.
[Thu Jan 21 13:08:37.921496 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290] Traceback (most recent call last):
[Thu Jan 21 13:08:37.921560 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/srv/modoboa/instance/instance/wsgi.py", line 16, in <module>
[Thu Jan 21 13:08:37.921568 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     application = get_wsgi_application()
[Thu Jan 21 13:08:37.921577 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Thu Jan 21 13:08:37.921582 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     django.setup(set_prefix=False)
[Thu Jan 21 13:08:37.921589 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3/dist-packages/django/__init__.py", line 22, in setup
[Thu Jan 21 13:08:37.921595 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Jan 21 13:08:37.921602 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 56, in __getattr__
[Thu Jan 21 13:08:37.921607 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     self._setup(name)
[Thu Jan 21 13:08:37.921614 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 41, in _setup
[Thu Jan 21 13:08:37.921620 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     self._wrapped = Settings(settings_module)
[Thu Jan 21 13:08:37.921626 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 110, in __init__
[Thu Jan 21 13:08:37.921632 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Jan 21 13:08:37.921639 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Thu Jan 21 13:08:37.921644 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Jan 21 13:08:37.921661 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Thu Jan 21 13:08:37.921668 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Thu Jan 21 13:08:37.921675 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Thu Jan 21 13:08:37.921682 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Thu Jan 21 13:08:37.921689 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Thu Jan 21 13:08:37.921695 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Thu Jan 21 13:08:37.921702 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Thu Jan 21 13:08:37.921719 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290] ModuleNotFoundError: No module named 'instance'
[Thu Jan 21 13:08:37.699216 2021] [ssl:debug] [pid 15677] ssl_engine_kernel.c(383): [client x.x.x.x:56290] AH02034: Initial (No.1) HTTPS request received for child 0 (server mail.test.org:443)
[Thu Jan 21 13:08:37.699561 2021] [authz_core:debug] [pid 15677] mod_authz_core.c(820): [client x.x.x.x:56290] AH01626: authorization result of Require all granted: granted
[Thu Jan 21 13:08:37.699571 2021] [authz_core:debug] [pid 15677] mod_authz_core.c(820): [client x.x.x.x:56290] AH01626: authorization result of <RequireAny>: granted
[Thu Jan 21 13:08:37.699713 2021] [authz_core:debug] [pid 15677] mod_authz_core.c(820): [client x.x.x.x:56290] AH01626: authorization result of Require all granted: granted
[Thu Jan 21 13:08:37.699721 2021] [authz_core:debug] [pid 15677] mod_authz_core.c(820): [client x.x.x.x:56290] AH01626: authorization result of <RequireAny>: granted
[Thu Jan 21 13:08:37.728803 2021] [wsgi:info] [pid 15677] [client x.x.x.x:56290] mod_wsgi (pid=15677, process='', application='mail.test.org|'): Loading Python script file '/srv/modoboa/instance/instance/wsgi.py'.
[Thu Jan 21 13:08:37.920838 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290] mod_wsgi (pid=15677): Failed to exec Python script file '/srv/modoboa/instance/instance/wsgi.py'.
[Thu Jan 21 13:08:37.920887 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290] mod_wsgi (pid=15677): Exception occurred processing WSGI script '/srv/modoboa/instance/instance/wsgi.py'.
[Thu Jan 21 13:08:37.921496 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290] Traceback (most recent call last):
[Thu Jan 21 13:08:37.921560 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/srv/modoboa/instance/instance/wsgi.py", line 16, in <module>
[Thu Jan 21 13:08:37.921568 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     application = get_wsgi_application()
[Thu Jan 21 13:08:37.921577 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Thu Jan 21 13:08:37.921582 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     django.setup(set_prefix=False)
[Thu Jan 21 13:08:37.921589 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3/dist-packages/django/__init__.py", line 22, in setup
[Thu Jan 21 13:08:37.921595 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Jan 21 13:08:37.921602 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 56, in __getattr__
[Thu Jan 21 13:08:37.921607 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     self._setup(name)
[Thu Jan 21 13:08:37.921614 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 41, in _setup
[Thu Jan 21 13:08:37.921620 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     self._wrapped = Settings(settings_module)
[Thu Jan 21 13:08:37.921626 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 110, in __init__
[Thu Jan 21 13:08:37.921632 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Jan 21 13:08:37.921639 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Thu Jan 21 13:08:37.921644 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Jan 21 13:08:37.921661 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Thu Jan 21 13:08:37.921668 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Thu Jan 21 13:08:37.921675 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Thu Jan 21 13:08:37.921682 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Thu Jan 21 13:08:37.921689 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Thu Jan 21 13:08:37.921695 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Thu Jan 21 13:08:37.921702 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Thu Jan 21 13:08:37.921719 2021] [wsgi:error] [pid 15677] [client x.x.x.x:56290] ModuleNotFoundError: No module named 'instance'

```
Apache2 config
```
<IfModule mod_ssl.c>
<VirtualHost _default_:443>
        ServerAdmin webmaster@localhost
        ServerName mail.test.org
#       <ifModule mpm_itk_module>
#               AssignUserId modoboa modoboa
#       </IfModule>
        DocumentRoot /srv/modoboa/instance/

        Alias /media/ /srv/modoboa/instance/media/
        <Directory /srv/modoboa/instance/media>
                Require all granted
        </Directory>

        Alias /sitestatic/ /srv/modoboa/instance/sitestatic/
        <Directory /srv/modoboa/instance/sitestatic>
                Require all granted
        </Directory>

        <Directory /srv/modoboa/instance/>
                Require all granted
        </Directory>

        WSGIScriptAlias / /srv/modoboa/instance/instance/wsgi.py
#       WSGIDaemonProcess mail.test.org python-path=/srv/modoboa:/srv/modoboa/env/lib/python3.7/site-packages
#       WSGIProcessGroup mail.test.org

        # Pass Authorization header to enable API usage:
        WSGIPassAuthorization On

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel debug

        LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b" common_forwarded
        ErrorLog  ${APACHE_LOG_DIR}/mail.test.org_error.log
        CustomLog ${APACHE_LOG_DIR}/mail.test.org_forwarded.log common_forwarded
        CustomLog ${APACHE_LOG_DIR}/mail.test.org.log combined env=!dontlog
        CustomLog ${APACHE_LOG_DIR}/mail.test.org.log combined

        DirectoryIndex index.php index.html
        Options FollowSymLinks
        RewriteEngine on
        HttpProtocolOptions Unsafe

        SSLCertificateFile /etc/letsencrypt/live/mail.test.org/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mail.test.org/privkey.pem
</VirtualHost>
</IfModule>
```

**Comment by NA7KR** [comment]
Fix it :
WSGIDaemonProcess mail.nerderlands.net python-path=/srv/modoboa/instance:/srv/modoboa/env/lib/python3.7/site-packages
