### ISSUE TITLE
manage.py modo check_mx (cron job) throws python error (mails every 30 mins.)

### ISSUE THREAD

**Issue by mas1701** [modoboa/modoboa#2246]
# Impacted versions

* OS Type: Debian
* OS Version: 10
* Database Type: MySQL
* Database version: 10.3.27-MariaDB-0+deb10u1
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx
* python --version: Python 3.7.3

# Steps to reproduce

* Do a default install of Modoboa on Debian 10.
* [Using "mailsrv" instead of "mail" as the mail server's subdomain. Using Let's Encrypt.]
* Define valid MX servers in Modoboa: mailsrv.MY-DOMAIN-HERE.de mailin.MY-DOMAIN-HERE.de
* Set up a first mail domain for testing (modoboa.MY-DOMAIN-HERE.de)

# Current behavior

DNS Status stuck at checks pending (Erwarte Prüfungen).
Throws error and generates a mail every 30 mins. containing this:

```
Subject: Cron <root@mailsrv>    $PYTHON $INSTANCE/manage.py modo check_mx
X-Cron-Env: <PYTHON=/srv/modoboa/env/bin/python>
X-Cron-Env: <INSTANCE=/srv/modoboa/instance>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>

Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 21, in <module>
    main()
  File "/srv/modoboa/instance/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.7/site-packages/modoboa/admin/management/commands/modo.py", line 50, in execute
    return options.pop('command').execute(*args, **options)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python3.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 296, in handle
    self.check_domain(domain, **options)
  File "/srv/modoboa/env/lib/python3.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 219, in check_domai
n
    self.check_valid_mx(domain, mx_list, **options)
  File "/srv/modoboa/env/lib/python3.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 159, in check_valid
_mx
    valid_mxs = self.valid_mxs
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/modoboa/env/lib/python3.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 44, in valid_mxs
    for v in valid_mxs.split() if v.strip()]
  File "/srv/modoboa/env/lib/python3.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 44, in <listcomp>
    for v in valid_mxs.split() if v.strip()]
  File "/usr/lib/python3.7/ipaddress.py", line 84, in ip_network
    address)
ValueError: 'mailsrv.MY-DOMAIN-HERE.de' does not appear to be an IPv4 or IPv6 network
```

# Expected behavior

Running check_mx without problems and with no mail to root every 30 mins.

**Comment by Ryvix** [comment]
Had this issue too. Discovered you have to set your Valid MXs to IP addresses instead of hostnames. You can do this in the dashboard under Modoboa > Parameters > Administration > Valid MXs

See #1664
