### ISSUE TITLE
bug in password change

### ISSUE THREAD

**Issue by NESC1US** [modoboa/modoboa#2357]
/srv/modoboa/env/bin/python3 /srv/modoboa/instance/manage.py changepassword user@mail.bla
```
Changing password for user 'user@mail.bla'
Password: 
Password (again): 
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 21, in <module>
    main()
  File "/srv/modoboa/instance/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/contrib/auth/management/commands/changepassword.py", line 72, in handle
    u.set_password(p1)
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/core/models.py", line 133, in set_password
    account=self, password=raw_value, created=self.pk is None)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/srv/modoboa/env/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa_pdfcredentials/handlers.py", line 22, in password_updated
    "generate_at_creation")
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/parameters/tools.py", line 182, in get_global_parameter
    return get_localconfig().parameters.get_value(name, app=app, **kwargs)
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/parameters/tools.py", line 117, in get_value
    default = registry.get_default(self._level, app, parameter)
  File "/srv/modoboa/env/lib/python3.6/site-packages/modoboa/parameters/tools.py", line 86, in get_default
    raise NotDefined(app)
modoboa.parameters.tools.NotDefined: Application modoboa_pdfcredentials not registered.
```
@OliverGee Looks like there is an issue in this case... As a workaround, comment out the 'modoboa_pdfcredentials' line in settings.py (inside the MODOBOA_APPS variable), run the command and uncomment the line.

_Originally posted by @tonioo in https://github.com/modoboa/modoboa/issues/1617#issuecomment-439381728_

..it would be nice to have it fixed.

**Comment by NESC1US** [comment]
i don't want to waste time with this project anymore, it's hardly working even with everything in default
