### ISSUE TITLE
Modoboa does not run on Python 3.9 (deprecated attribute alias)

### ISSUE THREAD

**Issue by olaf7** [modoboa/modoboa#2366]
Debian stable (Bullseye) 11.0
modoboa 1.17.0 in a virtualenv
Problem started after upgrading Debian Buster (recent old stable) to Bullseye which also moved Python3 from 3.7 to 3.9
I removed python3.7-minimal and upgraded the virtualenv to python 3.9
Modoboa uses a deprecated function which is no longer available in 3.9 : https://docs.python.org/3.8/library/base64.html#base64.decodestring

EDIT: sorry, too quickly. It is a module (feedparser) issue

$ python3 manage.py migrate
Traceback (most recent call last):
  File "/srv/modoboa/env/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/management/base.py", line 387, in check
    all_issues = self._run_checks(
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/srv/modoboa/env/instance/instance/urls.py", line 4, in <module>
    url(r'', include('modoboa.urls')),
  File "/srv/modoboa/env/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/srv/modoboa/env/lib/python3.9/site-packages/modoboa/urls.py", line 16, in <module>
    from modoboa.core import signals as core_signals, views as core_views
  File "/srv/modoboa/env/lib/python3.9/site-packages/modoboa/core/views/__init__.py", line 12, in <module>
    from .dashboard import DashboardView
  File "/srv/modoboa/env/lib/python3.9/site-packages/modoboa/core/views/dashboard.py", line 3, in <module>
    import feedparser
  File "/srv/modoboa/env/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'

**Comment by olaf7** [comment]
Will Modoboa 1.17.0 run with Feedparser 6.x ? (to resolve this issue)

**Comment by linuxbabe** [comment]
Yes, I encounter the same problem. 

Feb 25, 2022

**Comment by grauschnabel** [comment]
If you are sure you have python 3.9.x installed you can simply change the line

```  
   _base64decode = getattr(base64, 'decodebytes', base64.decodestring) 
```

to 
```
   _base64decode = getattr(base64, 'decodebytes')
```
in your `/srv/modoboa/env/lib/python3.9/site-packages/feedparser.py`

To fix the module someone has to use the `hasattr` in an `if` - statement here.

**Comment by MrGeneration** [comment]
Or, instead of hotfixing manually, you could pin down the version to
```
feedparser==6.0.8
```
