### ISSUE TITLE
You have an error in your SQL syntax

### ISSUE THREAD

**Issue by ndoody** [modoboa/modoboa#2443]
### Discussed in https://github.com/modoboa/modoboa/discussions/2442

<div type='discussions-op-text'>

<sup>Originally posted by **ndoody** January 20, 2022</sup>
Hi, I had a few problems with the SQL database of my modoboa installation - before it was something about the collation but sure I didn't get time to fully investigate / fix. As my data has stayed pretty static, I've left with a working but unmanageable solution.

So now I really need to add some more mailboxes, I am trying to resolve all issues...so I upgraded to modoboa 1.17. I have run through the upgrade instructions, but I am trying to run the SQL migrate...just getting this error :- 

`root@svr1:/home/16o/svr1/modoboa/managemail # python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, core, dnstools, lib, limits, maillog, modoboa_amavis, modoboa_dmarc, modoboa_postfix_autoreply, modoboa_radicale, otp_static, otp_totp, relaydomains, reversion, sessions, sites, transport
Running migrations:
  Applying admin.0017_alarm...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL, `closed` datetime(6) NULL, `status` integer NOT NULL, `title` varc' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL, `closed` datetime(6) NULL, `status` integer NOT NULL, `title` varc' at line 1")
root@svr1:/home/16o/svr1/modoboa/managemail #`</div>

**Comment by ndoody** [comment]
I have attempted to dump the database using mysqldump, delete and recreate importing the data.  I've also tried to do a manual re-install of modoboa, copying over my settings.py file.

The data imports, and it looks fine - postfix / dovecot are working from the data.  But the migrate command, as part of the upgrade process, still fails with the admin.0017 SQL update.

**Comment by tonioo** [comment]
@ndoody Can you try the complete SQL query generating this error? (looking at mysql logs)

**Comment by ndoody** [comment]
`                 1499 Query     SHOW FULL TABLES
                 1499 Query     ALTER TABLE `postfix_relay_domains_relaydomain`
ADD COLUMN `creation` datetime(6) DEFAULT '2022-01-22 22:56:59.927314' NOT NULL
                 1499 Quit
`
Run it manually :- 

`mysql> use mail
Database changed
mysql> ALTER TABLE `postfix_relay_domains_relaydomain`
    -> ADD COLUMN `creation` datetime(6) DEFAULT '2022-01-22 22:56:59.927314' NOT NULL
    -> ;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) DEFAULT '2022-01-22 22:56:59.927314' NOT NULL' at line 2
`

**Comment by ndoody** [comment]
I replaced datetime(6) for DATETIME and it worked, on a test database...if I try to use datetime(6) it doesn't like it.

**Comment by ndoody** [comment]
So I resolved the datetime(6) issue, you have to have minimum of mysql 5.6 to support datetime(6)...I upgraded and we got past that error.

So I had some more errors talkiong about cannot set various keys, but re-running we got past all the constraints / key issues until no more migrations needed to be run.

Now I can get into the app, running 1.17.0 and a lot of things are working...a few things aren't.  NAmely I can't complete adding new users, I notice the SQL commands for this are :- 

NSERT INTO `core_user` (`last_login`, `is_superuser`, `first_name`, `last_name`, `date_joined`, `username`, `email`, `is_staff`, `is_active`, `is_local`, `master_user`, `password`, `language`, `phone_number`, `secondary_email`, `tfa_enabled`, `_parameters`) VALUES (NULL, 0, 'Neil', 'Doody', '2022-01-24 01:02:12.593119', 'neil@doody.uk', '', 0, 1, 1, 0, '{MD5-CRYPT}removed', 'en-us', NULL, NULL, 0, '{}'

This command succeeds.

Now we try to add some permissions to the permissions table like this :- 

INSERT INTO `limits_userobjectlimit` (`user_id`, `name`, `content_type_id`, `max_value`) VALUES (38, 'domains', 15, 0)

Then we get this error if I try to run this :- 

ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mail`.`limits_userobjectlimit`, CONSTRAINT `limits_userobjectlimit_user_id_f7747c74_fk_core_user_id` FOREIGN KEY (`user_id`) REFERENCES `core_user` (`id`))

Not sure what's wrong with that, the id field is correct int(11) type of 38 in the core_user table...the user was created.  The query above is trying to insert into this userobjectlimit table the value 38 in the column user_id which is also int(11) but it doesn't like it.

I feel my database is probably a bit messed up at this point, it's a years old installation through multiple upgrades and there was SQL corruption to contend with over time from fault hard drives.  I wanted to make a fresh database, see if I can drop just the data...but it seems the new database wants a varchar maximum size higher than what's allowable on mysql 5.6.  

ANy ideas, anything I can do to recreate a nice clean database with my existing data?  It's very small, so I can easily migrate it around.

**Comment by ndoody** [comment]
Definitely something wrong with the foreign keys and constraints, I tried to edit the one in question above...and it just gave me this error "ERROR 1215 (HY000): Cannot add foreign key constraint"...so I've taken the SQL command and re-run it, it won't let me run successfully :- 

ALTER TABLE `limits_userobjectlimit` ADD  CONSTRAINT `limits_userobjectlimit_user_id_f7747c74_fk_core_user_id` FOREIGN KEY (`user_id`) REFERENCES `mail`.`core_user`(`id`);
ERROR 1215 (HY000): Cannot add foreign key constraint

And this is the error I see repeatedly on all the migrations, so the constaints and keys are all broken for sure...a way to reubild them?

**Comment by ndoody** [comment]
Resolved that one, some tables were InnoDB and some MyISAM.  The foreign key constraints were being applied between InnoDB and MyISAM tables mixed, so were invalid.  The collation wasn't all utf8_general_ci on all tables so I've changed that too.

I had to set the default engine to InnoDB on mysqld to ensure new tables created were also InnoDB.

Now I rolled back the SQL table, and all the migrations from manage.py succeeded...and I can create new users.

I would still like to do some kind of health check, re-create my database so it's fully clean and don't have any more bugs later on.  If you could help?
