### ISSUE TITLE
Installation on Rocky Linux not possible

### ISSUE THREAD

**Issue by 42deluxe** [modoboa/modoboa#2474]
Installer says:

Traceback (most recent call last):
  File "./run.py", line 13, in <module>
    from modoboa_installer import package
  File "/root/modoboa-installer/modoboa_installer/package.py", line 121, in <module>
    backend = get_backend()
  File "/root/modoboa-installer/modoboa_installer/package.py", line 117, in get_backend
    "Sorry, this distribution is not supported yet.")
NotImplementedError: Sorry, this distribution is not supported yet.

Why?

Rocky Linux is 100% compatible to CentOS/RHEL.

**Comment by tonioo** [comment]
@42deluxe Because it requires work to test the installer on every possible distribution. Feel free to provide a PR to add support for this distribution if you can.
