### ISSUE TITLE
No module named collections.abc

### ISSUE THREAD

**Issue by lbayerlein** [modoboa/modoboa#2523]
Hi,

thanks for your great work. Modoboa makes email server management a lot easier. I upgraded (yes, I know it is quite old) from version 1.8 to 1.10 and stopped, because I receive following error:

```
(env)[modoboa@mail01l instance]$ python manage.py check
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_sievefilters/apps.py", line 13, in ready
    from . import handlers
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_sievefilters/handlers.py", line 9, in <module>
    from . import lib
  File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_sievefilters/lib.py", line 9, in <module>
    from sievelib.factory import FiltersSet
  File "/srv/modoboa/env/lib/python2.7/site-packages/sievelib/factory.py", line 14, in <module>
    from sievelib import commands
  File "/srv/modoboa/env/lib/python2.7/site-packages/sievelib/commands.py", line 23, in <module>
    from collections.abc import Iterable
ImportError: No module named abc
```

I changed every line and updated plugins first. But on managesieve, I am doing something wrong.

Here my module list:

```
(env)[modoboa@mail01l instance]$ pip list|grep modoboa
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
modoboa (1.10.0)
modoboa-amavis (1.2.0)
modoboa-contacts (0.5.0)
modoboa-dmarc (1.1.0)
modoboa-imap-migration (1.2.0)
modoboa-pdfcredentials (1.3.0)
modoboa-postfix-autoreply (1.4.0)
modoboa-radicale (1.2.0)
modoboa-sievefilters (1.4.0)
modoboa-stats (1.4.0)
modoboa-webmail (1.4.0)
You are using pip version 9.0.1, however version 22.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env)[modoboa@mail01l instance]$ pip list|grep sievelib
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
sievelib (1.2.1)
You are using pip version 9.0.1, however version 22.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I read https://bugzilla.redhat.com/show_bug.cgi?id=1793003. I have changed `/srv/modoboa/env/lib/python2.7/site-packages/sievelib/commands.py" manually for testing purposes. But it prints me ASCII errors, so I reverted this back to default.

Can you help me, please?

Thank you

**Comment by lbayerlein** [comment]
Downgrading sievelib solved my problem

```
$ pip install sievelib==0.9.2
```
