### ISSUE TITLE
Upgrading issue 1.17.0 to 2.0.1 on debian 10

### ISSUE THREAD

**Issue by HA-TB303** [modoboa/modoboa#2535]
# Impacted versions

* OS Type: Debian
* OS Version: 10
* Database Type: Postgres
* Database version: 11.16 (Debian 11.16-0+deb10u1)
* Modoboa: 1.17.0
* installer used: Yes?
* Webserver: Nginx

# Steps to reproduce
Installed modoboa some time ago using the installer as outlined here: https://www.linuxbabe.com/mail-server/debian-10-buster-modoboa

Yesterday I updated Debian 10 (apt update && apt upgrade) and followed upgrade instructions as outlined here: https://modoboa.readthedocs.io/en/latest/upgrade.html#
and after some fiddeling I ended up with:
```
michel@mail:/srv/modoboa/instance$ python3 manage.py migrate
Traceback (most recent call last):
  File "/home/michel/.local/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/michel/.local/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/michel/.local/lib/python3.7/site-packages/django/core/management/base.py", line 86, in wrapped
    saved_locale = translation.get_language()
  File "/home/michel/.local/lib/python3.7/site-packages/django/utils/translation/__init__.py", line 254, in get_language
    return _trans.get_language()
  File "/home/michel/.local/lib/python3.7/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/home/michel/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/michel/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/michel/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/modoboa/instance/instance/settings.py", line 361, in <module>
    from modoboa_amavis import settings as modoboa_amavis_settings
ModuleNotFoundError: No module named 'modoboa_amavis'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/michel/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/michel/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/michel/.local/lib/python3.7/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/home/michel/.local/lib/python3.7/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/home/michel/.local/lib/python3.7/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/michel/.local/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/michel/.local/lib/python3.7/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/michel/.local/lib/python3.7/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/michel/.local/lib/python3.7/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/michel/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/michel/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/michel/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/modoboa/instance/instance/settings.py", line 361, in <module>
    from modoboa_amavis import settings as modoboa_amavis_settings
ModuleNotFoundError: No module named 'modoboa_amavis'
michel@mail:/srv/modoboa/instance$ python manage.py migrate
  File "manage.py", line 16
    ) from exc
         ^
SyntaxError: invalid syntax
```

# Current behavior

# Expected behavior
The upgrade proces to work similar as the installer proces.

# Video/Screenshot link (optional)
Full logs here: https://github.com/modoboa/modoboa/discussions/2534

**Comment by tonioo** [comment]
Looks like you forgot to load the virtualenv before running the upgrade commands.

**Comment by HA-TB303** [comment]
Hi, 

Thanks for taking the time to help!

> Looks like you forgot to load the virtualenv before running the upgrade commands.

Ok. Did not know I needed that.
When installed, I just followed instructions as outlined here: 

`
> git clone https://github.com/modoboa/modoboa-installer
> cd modoboa-installer
> sudo ./run.py <your domain>
`

I didn't know this installed a python virtual environment.

**Comment by HA-TB303** [comment]
Hi, sorry I feel like a complete noob here when it comes to python venv.

Instructions:

> Upgrade
Modoboa
Warning

The new version you are going to install may need to modify your database. Before you start, make sure to backup everything!

Most of the time, upgrading your installation to a newer Modoboa version only requires a few actions. In every case, you will need to apply the general procedure first and then check if the version you are installing requires specific actions.

In case you use a dedicated user and/or a virtualenv, do not forget to use them:

> sudo -u <modoboa_user> -i
> source <virtuenv_path>/bin/activate

So I tried:

`sudo -u modoboa -i`

Then:

```
$ source /env/bin/activate
-sh: 29: source: not found
$ 
````

I'm afraid these instructions do not help me much.

**Comment by HA-TB303** [comment]
Ok after switching the user I have to use the bash command first.

Then all goes well until:

```
(env) modoboa@mail:~/instance$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, core, dnstools, lib, limits, maillog, modoboa_amavis, modoboa_contacts, modoboa_postfix_autoreply, modoboa_radicale, otp_static, otp_totp, relaydomains, reversion, sessions, sites, transport
Running migrations:
  Applying admin.0018_auto_20201204_0935... OK
  Applying admin.0019_update_disabled_accounts_aliases... OK
  Applying admin.0020_auto_20210130_2226...Traceback (most recent call last):
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.FeatureNotSupported: cannot alter type of a column used by a view or rule
DETAIL:  rule _RETURN on view dkim depends on column "name"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 535, in alter_field
    old_db_params, new_db_params, strict)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/backends/postgresql/schema.py", line 124, in _alter_field
    new_db_params, strict,
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 685, in _alter_field
    params,
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/srv/modoboa/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.NotSupportedError: cannot alter type of a column used by a view or rule
DETAIL:  rule _RETURN on view dkim depends on column "name"
```

The upgrade is not for the faint hearted ;)

**Comment by HA-TB303** [comment]
So googled some and then found these additional instruction which I was initially unable to like to my specific issue:

https://modoboa.readthedocs.io/en/latest/upgrade.html#migration-issue-for-postgres-opendkim-users
First step ok (drop the view).

Migration OK
 Then:
```
postgres-# CREATE OR REPLACE VIEW dkim AS
postgres-#   SELECT admin_domain.id,
postgres-#      admin_domain.name AS domain_name,
postgres-#      admin_domain.dkim_private_key_path AS private_key_path,
postgres-#      admin_domain.dkim_key_selector AS selector
postgres-#     FROM admin_domain
postgres-#    WHERE admin_domain.enable_dkim;
ERROR:  syntax error at or near "OR"
LINE 2: CREATE OR REPLACE VIEW dkim AS
```

I hope some clear instructions could shine some light on this upgrade situation :)

**Comment by HA-TB303** [comment]
Do to lack of community support, migrating to IRedMail. Modoboa is obviously not as "simple" is stated on the website.
