### ISSUE TITLE
Enable CardDAV on user webmail

### ISSUE THREAD

**Issue by Tradeforlife** [modoboa/modoboa#2626]
Hi

Installed the latest build from the install script as of (5/10/2022) on debian 11 LXC in proxmox.

When I go to the webmail URL and login as a normal user account I attempt to enable Synchronization Address book using CardDAV but it errors out.

Error : Taken from Dev mode in chrome
----Start of error--

(index):336 Uncaught TypeError: Cannot read properties of undefined (reading 'destroy')
    at HTMLInputElement.toggleSignatureEditor ((index):336:18)
    at HTMLDocument.dispatch (jquery.min.js:3:28337)
    at v.handle (jquery.min.js:3:25042)
    at Object.trigger (jquery.min.js:3:27423)
    at HTMLInputElement.<anonymous> (jquery.min.js:4:3107)
    at Function.each (jquery.min.js:3:5257)
    at init.each (jquery.min.js:3:2013)
    at init.trigger (jquery.min.js:4:3083)
    at b.fn.<computed> [as change] (jquery.min.js:5:8648)
    at HTMLDocument.<anonymous> ((index):343:53)

--End of error---

When I click the ((index):336:18) to takes me to the following.
![image](https://user-images.githubusercontent.com/79732984/193970488-e96a164a-7d5c-42bf-b863-a9001564b5e5.png)

If I leave the selection on NO and click save it works fine... the other options "Message Filters" "Quarantine" "webmail" options all update fine.

Sorry if that's not enough information..

**Comment by tonioo** [comment]
@Tradeforlife Could enable the HTML editor for the webmail and check again please?

**Comment by nichosi** [comment]
Hello, Tonioo

the problem is also present in the demo version on the website

https://demo.modoboa.org/

unable to enable CardDAV in web interface -- settings

have a nice day!

**Comment by tonioo** [comment]
@nichosi The demo has been fixed. Radicale setup was broken.

**Comment by tonioo** [comment]
@Tradeforlife Make sure Radicale server is running on your server.
