### ISSUE TITLE
Cannot complete migrate after running makemigrations

### ISSUE THREAD

**Issue by ndoody** [modoboa/modoboa#2645]
Hi, running modoboa 2.0.2 on FReeBSD 11.4 and mysql 5.7.37.

I have tried to upgrade some extensions manually, I realised that running pip install extension does not upgrade to the latest version...so I started with trying to upgrade modboa-amavis to 1.4.0 I ran the following :-

> pip install modoboa-amavis==1.4.0

Then I ran the following :-

> python manage.py migrate

I then received the red text about running makemigrations :-

Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, core, dnstools, lib, limits, maillog, modoboa_amavis, modoboa_dmarc, modoboa_postfix_autoreply, modoboa_radicale, otp_static, otp_totp, relaydomains, reversion, sessions, sites, transport
Running migrations:
  No migrations to apply.
  Your models in app(s): 'admin', 'core', 'dnstools', 'limits', 'maillog', 'modoboa_dmarc', 'modoboa_postfix_autoreply', 'modoboa_radicale', 'relaydomains', 'transport' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

So I ran the following:- 

> python manage.py makemigrations

Now if I try to complete teh migration, the first one succeeded (Applying admin.0021_auto_20221017_1109... OK) then the second failed:-

 Applying core.0023_auto_20221017_1109...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1833, "Cannot change column 'id': used in a foreign key constraint 'modoboa_contacts_category_user_id_4061c4f0_fk_core_user_id' of table 'mail.modoboa_contacts_category'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 244, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 608, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 765, in _alter_field
    self.execute(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1833, "Cannot change column 'id': used in a foreign key constraint 'modoboa_contacts_category_user_id_4061c4f0_fk_core_user_id' of table 'mail.modoboa_contacts_category'")

These are the changes that makemigrations has attempted to create:-

Migrations for 'admin':
  /usr/local/lib/python3.8/site-packages/modoboa/admin/migrations/0021_auto_20221017_1109.py
    - Alter field id on alarm
    - Alter field id on alias
    - Alter field id on aliasrecipient
    - Alter field id on dnsblresult
    - Alter field id on domain
    - Alter field id on domainalias
    - Alter field id on mailbox
    - Alter field id on mailboxoperation
    - Alter field id on mxrecord
    - Alter field id on senderaddress
Migrations for 'core':
  /usr/local/lib/python3.8/site-packages/modoboa/core/migrations/0023_auto_20221017_1109.py
    - Alter field id on extensionupdatehistory
    - Alter field id on localconfig
    - Alter field id on log
    - Alter field id on objectaccess
    - Alter field first_name on user
    - Alter field id on user
    - Alter field language on user
Migrations for 'dnstools':
  /usr/local/lib/python3.8/site-packages/modoboa/dnstools/migrations/0002_alter_dnsrecord_id.py
    - Alter field id on dnsrecord
Migrations for 'limits':
  /usr/local/lib/python3.8/site-packages/modoboa/limits/migrations/0007_auto_20221017_1109.py
    - Alter field id on domainobjectlimit
    - Alter field id on userobjectlimit
Migrations for 'maillog':
  /usr/local/lib/python3.8/site-packages/modoboa/maillog/migrations/0004_alter_maillog_id.py
    - Alter field id on maillog
Migrations for 'modoboa_dmarc':
  /usr/local/lib/python3.8/site-packages/modoboa_dmarc/migrations/0004_auto_20221017_1109.py
    - Alter field id on record
    - Alter field id on report
    - Alter field id on reporter
    - Alter field id on result
Migrations for 'modoboa_postfix_autoreply':
  /usr/local/lib/python3.8/site-packages/modoboa_postfix_autoreply/migrations/0009_auto_20221017_1109.py
    - Alter field id on arhistoric
    - Alter field id on armessage
Migrations for 'modoboa_radicale':
  /usr/local/lib/python3.8/site-packages/modoboa_radicale/migrations/0006_auto_20221017_1109.py
    - Alter field id on accessrule
    - Alter field id on sharedcalendar
    - Alter field id on usercalendar
Migrations for 'relaydomains':
  /usr/local/lib/python3.8/site-packages/modoboa/relaydomains/migrations/0010_alter_recipientaccess_id.py
    - Alter field id on recipientaccess
Migrations for 'transport':
  /usr/local/lib/python3.8/site-packages/modoboa/transport/migrations/0003_alter_transport_id.py
    - Alter field id on transport

**Comment by ndoody** [comment]
Exactly the query causing this issue is this :-

ALTER TABLE `core_user` MODIFY `id` bigint AUTO_INCREMENT NOT NULL;

Currently this field is set to int(11)

**Comment by ndoody** [comment]
I got out of my comfort zone and dug deep in mysql on this one.

I removed the indexes/foreign constraints referencing the columns that needed updating int he migration script.  Namely these columns were :-

modoboa_contacts_category.userid -> core_user.id
modoboa_contacts_contact.userid -> core_user.id

After removing the migration completed successfully, then I reapplied the foreign keys using the SQL I got from doing a SQL dump extract first :-

ALTER TABLE `modoboa_contacts_category` 
  ADD KEY `modoboa_contacts_category_user_id_4061c4f0_fk_core_user_id` (`user_id`),
  ADD CONSTRAINT `modoboa_contacts_category_user_id_4061c4f0_fk_core_user_id` FOREIGN KEY (`user_id`) REFERENCES `core_user` (`id`);

ALTER TABLE `modoboa_contacts_contact`
  ADD KEY `modoboa_contacts_contact_user_id_11f4f283_fk_core_user_id` (`user_id`),
  ADD CONSTRAINT `modoboa_contacts_contact_user_id_11f4f283_fk_core_user_id` FOREIGN KEY (`user_id`) REFERENCES `core_user` (`id`);

So now the migration passed and all of the latest plugins are installed, would you be grateful to know if this is the appropriate workaround?

**Comment by tonioo** [comment]
@ndoody You should not have to create migration files yourself, that's actually a bug since 2.0. A fix is ready for Modoboa (https://github.com/modoboa/modoboa/pull/2622) but I still need to update plugins. If you can wait a bit, it should be available soon

**Comment by ndoody** [comment]
> @ndoody You should not have to create migration files yourself, that's actually a bug since 2.0. A fix is ready for Modoboa (#2622) but I still need to update plugins. If you can wait a bit, it should be available soon

Thanks, I can wait of course - because everything is working right now, was only worried I hadn't done something that might cause database corruption.  So I'll check out your upgrade/fix when it's available as well.
