### ISSUE TITLE
Modoboa upgrade from 1.17.0 fails

### ISSUE THREAD

**Issue by karlisk** [modoboa/modoboa#2775]
# Impacted versions

* OS Type: Ubuntu 
* OS Version: 20.04.5 LTS
* Database Type: PostgreSQL
* Database version: 12
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
```
su - modoboa
source /srv/modoboa/env/bin/activate
pip install modoboa==2.0.3
cd instance/
python manage.py migrate
```

# Current behavior
```
(env) modoboa@mail:~/instance$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_postfix_autoreply/models.py", line 7, in <module>
    from django.utils.encoding import python_2_unicode_compatible, smart_text
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/srv/modoboa/env/lib/python3.8/site-packages/django/utils/encoding.py)
```

# Expected behavior
Upgrade process to complete

# Video/Screenshot link (optional)
![image](https://user-images.githubusercontent.com/2720782/216845189-a528fb60-b4db-4278-a381-456e287a1a20.png)
![image](https://user-images.githubusercontent.com/2720782/216845215-ac621c83-33c4-42e3-b529-cdf21a1143e3.png)
![image](https://user-images.githubusercontent.com/2720782/216845262-0a33771c-d90d-4b02-83a3-e32f26a7d921.png)
![image](https://user-images.githubusercontent.com/2720782/216845234-19b6dca9-c93d-4bdb-b9d6-eb3f30c3c64a.png)

**Comment by karlisk** [comment]
Attempting to upgrade to 2.0.0:
```
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_postfix_autoreply/models.py", line 7, in <module>
    from django.utils.encoding import python_2_unicode_compatible, smart_text
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/srv/modoboa/env/lib/python3.8/site-packages/django/utils/encoding.py)
```

**Comment by karlisk** [comment]
Situation has deteriorated. Dropping in favor of something else. This is just a complete mess.
