### ISSUE TITLE
Policyd doesn't start

### ISSUE THREAD

**Issue by Calypso971** [modoboa/modoboa#3036]
On Debian 12 we have Python 3.11. Policyd doesn't correctly start with this Python version. It seems modoboa uses aioredis, but I've seen some mentions that it is deprecated in Python 3.11

Traceback (most recent call last):
  File "/usr/local/modoboa/instance/manage.py", line 22, in <module>
    main()
  File "/usr/local/modoboa/instance/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/modoboa/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/modoboa/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/modoboa/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 257, in fetch_command
    klass = load_command_class(app_name, subcommand)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/modoboa/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/modoboa/env/lib/python3.11/site-packages/modoboa/policyd/management/commands/policy_daemon.py", line 11, in <module>
    from ... import core
  File "/usr/local/modoboa/env/lib/python3.11/site-packages/modoboa/policyd/core.py", line 11, in <module>
    import aioredis
  File "/usr/local/modoboa/env/lib/python3.11/site-packages/aioredis/__init__.py", line 1, in <module>
    from aioredis.client import Redis, StrictRedis
  File "/usr/local/modoboa/env/lib/python3.11/site-packages/aioredis/client.py", line 32, in <module>
    from aioredis.connection import (
  File "/usr/local/modoboa/env/lib/python3.11/site-packages/aioredis/connection.py", line 33, in <module>
    from .exceptions import (
  File "/usr/local/modoboa/env/lib/python3.11/site-packages/aioredis/exceptions.py", line 14, in <module>
    class TimeoutError(asyncio.TimeoutError, builtins.TimeoutError, RedisError):
TypeError: duplicate base class TimeoutError

Modoboa version is the latest one (2.1.2); just installed it a few days ago. Other machine running with Python 3.10 works with the same configuration without problems.

**Comment by Spitfireap** [comment]
Hi, it has been [fixed](https://github.com/modoboa/modoboa/pull/3026)  and will be available in next version.
