### ISSUE TITLE
Cannot import name 'ugettext_lazy' from 'django.utils.translation' 

### ISSUE THREAD

**Issue by TheAFKGamer10** [modoboa/modoboa#3100]
# Impacted versions 

* OS Type: Ubuntu
* OS Version: Ubuntu 22.04.3 LTS
* Database Type: PostgreSQL
* Database version: psql (PostgreSQL) 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
* Modoboa: 2.2.2
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
```
cd /srv/modoboa/instance
pip install modoboa==2.2.2
python manage.py migrate
```
# Current behavior
Error gets thrown, I googled the subject and it says that `ugettext_lazy` is not supported anymore. It occured during `python3 manage.py migrate` command.
```
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    main()
  File "/srv/modoboa/instance/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/srv/modoboa/env/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/srv/modoboa/env/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/srv/modoboa/env/lib/python3.10/site-packages/modoboa_amavis/models.py", line 16, in <module>
    from django.utils.translation import ugettext_lazy
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/srv/modoboa/env/lib/python3.10/site-packages/django/utils/translation/__init__.py)
```

# Expected behavior

Update is sucessful and updates to the lattest version.

**Comment by tonioo** [comment]
It's clearly mentioned in the upgrade instructions that you also need to update extensions.
https://modoboa.readthedocs.io/en/latest/upgrade.html#id2

**Comment by blloyd75** [comment]
I found this CLOSED error because I was searching for why i have so many errors.
I have modoboa_pdfcredentials 1.5.0, which is reporting as the newest version of that extension.   And I still see the error thrown from modoboa_pdfcredentials.

**Comment by tonioo** [comment]
@blloyd75 Looks like you missed some upgrade steps:
https://modoboa.readthedocs.io/en/latest/upgrade.html#id3

**Comment by jquiros2** [comment]
python 3.8.  How to tell which extension?  I did a manual pip-install to all extensions i could find in setting.py but no dice.  upgrading to 2.0.  could min python 3.9 be necessary, or 3.8 ok like it says in the docs?

(env) modoboa@voy:~/instance$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_amavis/models.py", line 16, in <module>
    from django.utils.translation import ugettext_lazy
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/srv/modoboa/env/lib/python3.8/site-packages/django/utils/translation/__init__.py)
