### ISSUE TITLE
Error on fresh install without CalmAV

### ISSUE THREAD

**Issue by H-A-L-I-S** [modoboa/modoboa#3149]
# Impacted versions

* OS Type: Debian/Ubuntu,
* OS Version: 12
* Database Type: PostgreSQL
* Database version: 15
* Modoboa: Newest/Fresh install (should be 2.2.3)
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Just install (with calmAV disabled)

# Current behavior

```
From: root@mail.DOMAIN.de (Cron Daemon)
To: root@mail.DOMAIN.de
Subject: Cron <root@localhost>    $PYTHON $INSTANCE/manage.py generate_rights
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <PYTHON=/srv/modoboa/env/bin/python>
X-Cron-Env: <INSTANCE=/srv/modoboa/instance>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
Message-Id: <2023122..........@mail.DOMAIN.de>
Date: Sat, 23 Dec 2023 .........................

Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    main()
  File "/srv/modoboa/instance/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/modoboa/env/lib/python3.11/site-packages/modoboa_radicale/management/commands/generate_rights.py", line 121, in handle
    path = param_tools.get_global_parameter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/modoboa/env/lib/python3.11/site-packages/modoboa/parameters/tools.py", line 258, in get_global_parameter
    return get_localconfig().parameters.get_value(name, app=app, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'parameters'

```

# Expected behavior

Successful installation

# Video/Screenshot link (optional)

**Comment by kisattinovels** [comment]
Just installed it, same thing.

**Comment by kisattinovels** [comment]
Had the same stuff, but  calmAV included. Re added the DNS records, then re-installed the modoboa on the existing installation, and now it works for me.

**Comment by H-A-L-I-S** [comment]
It was indeed an DNS issue. As improvement, the error message could contain the words "Check DNS configuration"
