### ISSUE TITLE
I can't send E-Mails

### ISSUE THREAD

**Issue by LOGODERKING** [modoboa/modoboa#3204]
# Impacted versions

* OS Type: Debian
* OS Version: 12
* Database Type: MySQL
* Database version: 15.1
* Modoboa: 2.2.3
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Send an Email over the Webmail and press "send" to get the error
# Current behavior
It's not sending an email and I keep getting this error:
```
Failed to load resource: the server responded with a status of 500 ()

Uncaught SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:3:4322)
    at Webmail.<anonymous> (webmail.js:1063:26)
    at Object.i (jquery.min.js:3:6336)
    at c (jquery.min.js:3:7857)
    at Object.fireWith [as rejectWith] (jquery.min.js:3:8658)
    at k (jquery.min.js:5:14040)
    at XMLHttpRequest.r (jquery.min.js:5:18226)
```

# Expected behavior
Normally it should just send the email
# Video/Screenshot link (optional)

![image](https://github.com/modoboa/modoboa/assets/85257897/f39db9ea-4f3e-41ac-bfe4-4756ae6f95b8)

**Comment by nuruddin2702** [comment]
I have sama problem
