### ISSUE TITLE
Problems after upgrade 2.0.4 to 2.1.0

### ISSUE THREAD

**Issue by antoweb** [modoboa/modoboa#3236]
# Impacted versions

* OS Type: Ubuntu 20.04.6 LTS (Focal Fossa)
* OS Version: 20.04.6 LTS (Focal Fossa)
* Database Type: PostgreSQL 12
* Database version: 12
* Modoboa: 2.1.0
* installer used: No
* Webserver: Nginx

# Steps to reproduce

Install modoboa==2.1.0
Followed steps here:
https://modoboa.readthedocs.io/en/latest/upgrade.html#id5
Update all modules
![immagine](https://github.com/modoboa/modoboa/assets/32364871/b7b05fbd-1c47-4f2e-a9db-6dbb5f517edb)

run
> python manage.py migrate
> python manage.py collectstatic
> python manage.py check --deploy

# Current behavior

I cannot edit or delete an existing mailbox  but i can create a new one, also this created mailbox i cannot delete or editing
i receive internal error
![immagine](https://github.com/modoboa/modoboa/assets/32364871/1ee8b812-cc73-48b3-8d3f-199d966f6732)

And when launch python manage.py generate_postfix_maps --destdir /etc/postfix error is:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'modoboa.dmarc'

# Expected behavior
I can create and manage old and new mailbox

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
@antoweb Can you set DEBUG to True inside settings.py, reload uwsgi and try again? (look at the browser console to get more info
And about the shell command issue, did you launch it using the vitual env of Modoboa? (/srv/modoboa/env)

**Comment by antoweb** [comment]
Hello @tonioo i had set debig to true but doesnt appear any message on browser.
The command was launched in venv

**Comment by Spitfireap** [comment]
> ModuleNotFoundError: No module named 'modoboa.dmarc'

@antoweb can you restart uWSGI? modoboa.dmarc module should be recognized in 2.1.0...

**Comment by antoweb** [comment]
I am already restarted the service after migrate and deploy command.
I have to retart another Time?

**Comment by Spitfireap** [comment]
Can you share the MODOBOA_APPS in your settings.py ?

**Comment by antoweb** [comment]
MODOBOA_APPS = (
    'modoboa',
    'modoboa.core',
    'modoboa.lib',
    'modoboa.admin',
    'modoboa.transport',
    'modoboa.relaydomains',
    'modoboa.limits',
    'modoboa.parameters',
    'modoboa.dnstools',
    'modoboa.policyd',
    'modoboa.maillog',
    # Modoboa extensions here.
    'modoboa_amavis',
    'modoboa_pdfcredentials',
    'modoboa_postfix_autoreply',
    'modoboa_sievefilters',
    'modoboa_webmail',
    'modoboa_contacts',
    'modoboa_radicale',

)

**Comment by tonioo** [comment]
@antoweb It seems you forgot to follow upgrade instructions for 2.1.0:
https://modoboa.readthedocs.io/en/latest/upgrade.html#id5

**Comment by antoweb** [comment]
Hello,
No i have put the correct items in modoboa_apps. T'ha text i have sent Is a rollback.

**Comment by antoweb** [comment]
The errore was:

No module modoboa.dmarc found

**Comment by Spitfireap** [comment]
> No module modoboa.dmarc found

This means the update did not successfully install modoboa 2.1.0. Can you try again ?

**Comment by Spitfireap** [comment]
Hi, Have managed to get it working ? @antoweb

**Comment by antoweb** [comment]
already tried same error
