### ISSUE TITLE
Installer: Ubuntu 24.04 - pkgutil has no attribute ImpImporter

### ISSUE THREAD

**Issue by rufinus** [modoboa/modoboa#3256]
# Impacted versions

* OS Type: Ubuntu
* OS Version: 24.04 (Nobel)
* installer used: Yes
* # python3 --version
Python 3.12.3

# Steps to reproduce

sudo ./run.py mail.mydomain.tld

# Current behavior

```
Welcome to Modoboa installer!

Checking the installer...
Installer seems up to date!
Checks complete

Notice:
It is recommanded to run this installer on a FRESHLY installed server.
(ie. with nothing special already installed on it)

Warning:
Before you start the installation, please make sure the following DNS records exist for domain 'mail.cwd.at':
  mail IN A   <IP ADDRESS OF YOUR SERVER>
     @ IN MX  mail.mydomain.tld

Your mail server will be installed with the following components:
fail2ban modoboa automx amavis clamav dovecot nginx razor postfix postwhite spamassassin uwsgi radicale opendkim
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new self-signed certificate
Installing amavis
/root/modoboa-installer/modoboa_installer/database.py:106: SyntaxWarning: invalid escape sequence '\|'
  "psql -lqt | cut -d \| -f 1 | grep -w {} | wc -l"
/root/modoboa-installer/modoboa_installer/python.py:124: SyntaxWarning: invalid escape sequence '\<'
  install_packages(["pip", "setuptools\<58.0.0"], venv=path, upgrade=True)
Installing spamassassin
Installing razor
Installing clamav
Installing fail2ban
Installing modoboa
/root/modoboa-installer/modoboa_installer/scripts/modoboa.py:105: SyntaxWarning: invalid escape sequence '\<'
  req_version = req_version.replace("<", "\<")
/root/modoboa-installer/modoboa_installer/scripts/modoboa.py:106: SyntaxWarning: invalid escape sequence '\>'
  req_version = req_version.replace(">", "\>")
b'Traceback (most recent call last):\n  File "/srv/modoboa/env/bin/modoboa-admin.py", line 3, in <module>\n    from modoboa.core.commands import handle_command_line\n  File "/srv/modoboa/env/lib/python3.12/site-packages/modoboa/__init__.py", line 3, in <module>\n    from pkg_resources import DistributionNotFound, get_distribution\n  File "/srv/modoboa/env/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2158, in <module>\n    register_finder(pkgutil.ImpImporter, find_on_path)\n                    ^^^^^^^^^^^^^^^^^^^\nAttributeError: module \'pkgutil\' has no attribute \'ImpImporter\'. Did you mean: \'zipimporter\'?\n'
```

Is Ubuntu 24.04 not yet supported? Any other way to help debug this?

**Comment by tonioo** [comment]
That's right, this version of Ubuntu is not supported yet.

**Comment by tonioo** [comment]
@rufinus Could check with this branch: https://github.com/modoboa/modoboa-installer/pull/557 ?

**Comment by rufinus** [comment]
> @rufinus Could check with this branch: [modoboa/modoboa-installer#557](https://github.com/modoboa/modoboa-installer/pull/557) ?

Looks good, installer completes system seem to be working. Thank you.
