### ISSUE TITLE
Import of aliases broken

### ISSUE THREAD

**Issue by ddt-consult** [modoboa/modoboa#818]
The import of aliases into modoboa 1.4.2 is broken.
If I try to import one domain with one account and one alias pointing to this account into a fresh installation of modoboa (see CSV files below), the import of the identities fails with "Local recipient not found".
AFAIKT in Alias.set_recipients() modoboa checks whether the target for an alias already exists in the DB. If that's not the case, it checks whether the target is itlself another alias. If that's not the case either, it raises an exception instead of creating the target.
Just for testing I commented lines 133-139 in alias.py, i. e.

``` python
                    # if rcpt is None:
                    #     raise NotFound(
                    #         _("Local recipient {}@{} not found")
                    #         .format(local_part, domname)
                    #     )
                    # if rcpt.address == self.address:
                    #     raise Conflict
```

and the import of my identities file succeeded.

domains.csv:
`domain;ddt-consult.de;100000;True`

identities.csv:
`account;admin@ddt-consult.de;{SHA512-CRYPT}$6$rounds=70000$yOfLHTrqigEMkPlW$.6Oq0b1bmcrfk8OcuDNzZYbOEVVgkcmrnPH3Mmqwyg6qlBjxVbRX7fGwxWUqYsimYxnGABXME4Ba8xt.1KaTK/;;;True;DomainAdmins;admin@ddt-consult.de;100000;ddt-consult.de
alias;abuse@ddt-consult.de;True;admin@ddt-consult.de`

**Comment by tonioo** [comment]
Hi,
I can't reproduce your issue with 1.4.2. Are you importing from the CLI or from the interface ?

**Comment by ddt-consult** [comment]
From the command line.

If you just copied the identities.csv above from this webpage, the linefeed between the account and the alias line may get eaten. Then you would have just one line in the CSV and only the account would get created but not the alias (which triggers the error).

BTW: that's the traceback I get when I try to import this identities.csv:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/share/modoboa-1.4.2/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/share/modoboa-1.4.2/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/share/modoboa-1.4.2/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/share/modoboa-1.4.2/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/share/modoboa-1.4.2/venv/local/lib/python2.7/site-packages/modoboa/admin/management/commands/import_identities.py", line 34, in handle
    import_csv(filename, kwargs)
  File "/usr/local/share/modoboa-1.4.2/venv/local/lib/python2.7/site-packages/modoboa/admin/management/commands/_import.py", line 43, in import_csv
    fct(superadmin, row, options)
  File "/usr/local/share/modoboa-1.4.2/venv/local/lib/python2.7/site-packages/modoboa/admin/lib.py", line 147, in import_alias
    _import_alias(user, row, expected_elements=4)
  File "/usr/local/share/modoboa-1.4.2/venv/local/lib/python2.7/site-packages/modoboa/admin/lib.py", line 143, in _import_alias
    alias.from_csv(user, row, **kwargs)
  File "/usr/local/share/modoboa-1.4.2/venv/local/lib/python2.7/site-packages/modoboa/admin/models/alias.py", line 177, in from_csv
    self.set_recipients([raddress.strip() for raddress in row[3:]])
  File "/usr/local/share/modoboa-1.4.2/venv/local/lib/python2.7/site-packages/modoboa/admin/models/alias.py", line 134, in set_recipients
    .format(local_part, domname)
modoboa.lib.exceptions.NotFound: Local recipient admin@ddt-consult.de not found
```

**Comment by tonioo** [comment]
I still can't reproduce it. Which database do you use ? Have you made modifications to your settings file ?

**Comment by ddt-consult** [comment]
DB: MySQL.
Of course I have made modifications to settings.py: ALLOWED_HOSTS, LANGUAGE_CODE, ...

**Comment by tonioo** [comment]
Would it be easy for you to check the behaviour using a postgresql database ?

**Comment by tonioo** [comment]
@ddt-consult ping

**Comment by dirtyhillbilly** [comment]
I have the same problem. The misleading part is that when an identity is created, the associated mailbox is not.

**Comment by tonioo** [comment]
@dirtyhillbilly Can you provide the file you used for import?

**Comment by dirtyhillbilly** [comment]
The file I used lacked the "address" part, thus creating the account didn't create the mailbox.
Things like that work as expected :
```
account;xxx@foo.net;{SHA512-CRYPT}$6$rounds=70000$fybLy/WWfW.I/fx3$yR2zDgcN549pE7EJelnYYuXA/TLO.m53ssk/eiajieVQF7/E5B3hAyD6456sdGf3KvxZuEhQ1aQfZOzaB1407.;firstname;lastname;SimpleUser;True;xxx@foo.net
```
